// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fp_sop,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xa7a12tcsg325-1q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.627125,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=644,HLS_SYN_LUT=3880,HLS_VERSION=2018_2}" *)

module fp_sop (
        ap_clk,
        ap_rst,
        kernel_patch_0_V,
        kernel_patch_1_V,
        kernel_patch_2_V,
        kernel_patch_3_V,
        kernel_patch_4_V,
        kernel_patch_5_V,
        kernel_patch_6_V,
        kernel_patch_7_V,
        kernel_patch_8_V,
        kernel_patch_9_V,
        kernel_patch_10_V,
        kernel_patch_11_V,
        kernel_patch_12_V,
        kernel_patch_13_V,
        kernel_patch_14_V,
        kernel_patch_15_V,
        kernel_patch_16_V,
        kernel_patch_17_V,
        kernel_patch_18_V,
        kernel_patch_19_V,
        kernel_patch_20_V,
        kernel_patch_21_V,
        kernel_patch_22_V,
        kernel_patch_23_V,
        kernel_patch_24_V,
        kernel_patch_25_V,
        kernel_patch_26_V,
        kernel_patch_27_V,
        kernel_patch_28_V,
        kernel_patch_29_V,
        kernel_patch_30_V,
        kernel_patch_31_V,
        kernel_patch_32_V,
        kernel_patch_33_V,
        kernel_patch_34_V,
        kernel_patch_35_V,
        kernel_patch_36_V,
        kernel_patch_37_V,
        kernel_patch_38_V,
        kernel_patch_39_V,
        kernel_patch_40_V,
        kernel_patch_41_V,
        kernel_patch_42_V,
        kernel_patch_43_V,
        kernel_patch_44_V,
        kernel_patch_45_V,
        kernel_patch_46_V,
        kernel_patch_47_V,
        kernel_patch_48_V,
        pixel_window_0_V,
        pixel_window_1_V,
        pixel_window_2_V,
        pixel_window_3_V,
        pixel_window_4_V,
        pixel_window_5_V,
        pixel_window_6_V,
        pixel_window_7_V,
        pixel_window_8_V,
        pixel_window_9_V,
        pixel_window_10_V,
        pixel_window_11_V,
        pixel_window_12_V,
        pixel_window_13_V,
        pixel_window_14_V,
        pixel_window_15_V,
        pixel_window_16_V,
        pixel_window_17_V,
        pixel_window_18_V,
        pixel_window_19_V,
        pixel_window_20_V,
        pixel_window_21_V,
        pixel_window_22_V,
        pixel_window_23_V,
        pixel_window_24_V,
        pixel_window_25_V,
        pixel_window_26_V,
        pixel_window_27_V,
        pixel_window_28_V,
        pixel_window_29_V,
        pixel_window_30_V,
        pixel_window_31_V,
        pixel_window_32_V,
        pixel_window_33_V,
        pixel_window_34_V,
        pixel_window_35_V,
        pixel_window_36_V,
        pixel_window_37_V,
        pixel_window_38_V,
        pixel_window_39_V,
        pixel_window_40_V,
        pixel_window_41_V,
        pixel_window_42_V,
        pixel_window_43_V,
        pixel_window_44_V,
        pixel_window_45_V,
        pixel_window_46_V,
        pixel_window_47_V,
        pixel_window_48_V,
        sop_enable,
        out_valid,
        out_valid_ap_vld,
        out_val_V,
        out_val_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input  [7:0] kernel_patch_0_V;
input  [7:0] kernel_patch_1_V;
input  [7:0] kernel_patch_2_V;
input  [7:0] kernel_patch_3_V;
input  [7:0] kernel_patch_4_V;
input  [7:0] kernel_patch_5_V;
input  [7:0] kernel_patch_6_V;
input  [7:0] kernel_patch_7_V;
input  [7:0] kernel_patch_8_V;
input  [7:0] kernel_patch_9_V;
input  [7:0] kernel_patch_10_V;
input  [7:0] kernel_patch_11_V;
input  [7:0] kernel_patch_12_V;
input  [7:0] kernel_patch_13_V;
input  [7:0] kernel_patch_14_V;
input  [7:0] kernel_patch_15_V;
input  [7:0] kernel_patch_16_V;
input  [7:0] kernel_patch_17_V;
input  [7:0] kernel_patch_18_V;
input  [7:0] kernel_patch_19_V;
input  [7:0] kernel_patch_20_V;
input  [7:0] kernel_patch_21_V;
input  [7:0] kernel_patch_22_V;
input  [7:0] kernel_patch_23_V;
input  [7:0] kernel_patch_24_V;
input  [7:0] kernel_patch_25_V;
input  [7:0] kernel_patch_26_V;
input  [7:0] kernel_patch_27_V;
input  [7:0] kernel_patch_28_V;
input  [7:0] kernel_patch_29_V;
input  [7:0] kernel_patch_30_V;
input  [7:0] kernel_patch_31_V;
input  [7:0] kernel_patch_32_V;
input  [7:0] kernel_patch_33_V;
input  [7:0] kernel_patch_34_V;
input  [7:0] kernel_patch_35_V;
input  [7:0] kernel_patch_36_V;
input  [7:0] kernel_patch_37_V;
input  [7:0] kernel_patch_38_V;
input  [7:0] kernel_patch_39_V;
input  [7:0] kernel_patch_40_V;
input  [7:0] kernel_patch_41_V;
input  [7:0] kernel_patch_42_V;
input  [7:0] kernel_patch_43_V;
input  [7:0] kernel_patch_44_V;
input  [7:0] kernel_patch_45_V;
input  [7:0] kernel_patch_46_V;
input  [7:0] kernel_patch_47_V;
input  [7:0] kernel_patch_48_V;
input  [7:0] pixel_window_0_V;
input  [7:0] pixel_window_1_V;
input  [7:0] pixel_window_2_V;
input  [7:0] pixel_window_3_V;
input  [7:0] pixel_window_4_V;
input  [7:0] pixel_window_5_V;
input  [7:0] pixel_window_6_V;
input  [7:0] pixel_window_7_V;
input  [7:0] pixel_window_8_V;
input  [7:0] pixel_window_9_V;
input  [7:0] pixel_window_10_V;
input  [7:0] pixel_window_11_V;
input  [7:0] pixel_window_12_V;
input  [7:0] pixel_window_13_V;
input  [7:0] pixel_window_14_V;
input  [7:0] pixel_window_15_V;
input  [7:0] pixel_window_16_V;
input  [7:0] pixel_window_17_V;
input  [7:0] pixel_window_18_V;
input  [7:0] pixel_window_19_V;
input  [7:0] pixel_window_20_V;
input  [7:0] pixel_window_21_V;
input  [7:0] pixel_window_22_V;
input  [7:0] pixel_window_23_V;
input  [7:0] pixel_window_24_V;
input  [7:0] pixel_window_25_V;
input  [7:0] pixel_window_26_V;
input  [7:0] pixel_window_27_V;
input  [7:0] pixel_window_28_V;
input  [7:0] pixel_window_29_V;
input  [7:0] pixel_window_30_V;
input  [7:0] pixel_window_31_V;
input  [7:0] pixel_window_32_V;
input  [7:0] pixel_window_33_V;
input  [7:0] pixel_window_34_V;
input  [7:0] pixel_window_35_V;
input  [7:0] pixel_window_36_V;
input  [7:0] pixel_window_37_V;
input  [7:0] pixel_window_38_V;
input  [7:0] pixel_window_39_V;
input  [7:0] pixel_window_40_V;
input  [7:0] pixel_window_41_V;
input  [7:0] pixel_window_42_V;
input  [7:0] pixel_window_43_V;
input  [7:0] pixel_window_44_V;
input  [7:0] pixel_window_45_V;
input  [7:0] pixel_window_46_V;
input  [7:0] pixel_window_47_V;
input  [7:0] pixel_window_48_V;
input   sop_enable;
output   out_valid;
output   out_valid_ap_vld;
output  [15:0] out_val_V;
output   out_val_V_ap_vld;

reg out_valid_ap_vld;
reg out_val_V_ap_vld;

wire   [0:0] sop_enable_read_read_fu_344_p2;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [10:0] tmp_84_reg_3765;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_139_reg_3770;
reg   [10:0] tmp_86_reg_3775;
reg   [0:0] tmp_140_reg_3780;
reg   [10:0] tmp_88_reg_3785;
reg   [0:0] tmp_141_reg_3790;
wire  signed [11:0] p_Val2_98_fu_1088_p2;
reg  signed [11:0] p_Val2_98_reg_3795;
wire    ap_CS_fsm_state3;
wire  signed [11:0] p_Val2_99_fu_1134_p2;
reg  signed [11:0] p_Val2_99_reg_3800;
wire  signed [11:0] p_Val2_100_fu_1180_p2;
reg  signed [11:0] p_Val2_100_reg_3805;
wire  signed [11:0] p_Val2_101_fu_1226_p2;
reg  signed [11:0] p_Val2_101_reg_3810;
wire  signed [11:0] p_Val2_102_fu_1272_p2;
reg  signed [11:0] p_Val2_102_reg_3815;
wire  signed [11:0] p_Val2_103_fu_1318_p2;
reg  signed [11:0] p_Val2_103_reg_3820;
wire  signed [11:0] p_Val2_104_fu_1364_p2;
reg  signed [11:0] p_Val2_104_reg_3825;
wire  signed [11:0] p_Val2_105_fu_1410_p2;
reg  signed [11:0] p_Val2_105_reg_3830;
wire  signed [11:0] p_Val2_106_fu_1456_p2;
reg  signed [11:0] p_Val2_106_reg_3835;
wire  signed [11:0] p_Val2_107_fu_1502_p2;
reg  signed [11:0] p_Val2_107_reg_3840;
wire  signed [11:0] p_Val2_108_fu_1548_p2;
reg  signed [11:0] p_Val2_108_reg_3845;
wire  signed [11:0] p_Val2_109_fu_1594_p2;
reg  signed [11:0] p_Val2_109_reg_3850;
wire  signed [11:0] p_Val2_110_fu_1640_p2;
reg  signed [11:0] p_Val2_110_reg_3855;
wire  signed [11:0] p_Val2_111_fu_1686_p2;
reg  signed [11:0] p_Val2_111_reg_3860;
wire  signed [11:0] p_Val2_112_fu_1732_p2;
reg  signed [11:0] p_Val2_112_reg_3865;
wire  signed [11:0] p_Val2_113_fu_1778_p2;
reg  signed [11:0] p_Val2_113_reg_3870;
wire  signed [11:0] p_Val2_114_fu_1824_p2;
reg  signed [11:0] p_Val2_114_reg_3875;
wire  signed [11:0] p_Val2_115_fu_1870_p2;
reg  signed [11:0] p_Val2_115_reg_3880;
wire  signed [11:0] p_Val2_116_fu_1916_p2;
reg  signed [11:0] p_Val2_116_reg_3885;
wire  signed [11:0] p_Val2_117_fu_1962_p2;
reg  signed [11:0] p_Val2_117_reg_3890;
wire  signed [11:0] p_Val2_118_fu_2008_p2;
reg  signed [11:0] p_Val2_118_reg_3895;
wire  signed [11:0] p_Val2_119_fu_2054_p2;
reg  signed [11:0] p_Val2_119_reg_3900;
wire  signed [11:0] p_Val2_120_fu_2100_p2;
reg  signed [11:0] p_Val2_120_reg_3905;
wire  signed [11:0] p_Val2_121_fu_2146_p2;
reg  signed [11:0] p_Val2_121_reg_3910;
wire  signed [11:0] p_Val2_122_fu_2192_p2;
reg  signed [11:0] p_Val2_122_reg_3915;
wire  signed [11:0] p_Val2_123_fu_2238_p2;
reg  signed [11:0] p_Val2_123_reg_3920;
wire  signed [11:0] p_Val2_124_fu_2284_p2;
reg  signed [11:0] p_Val2_124_reg_3925;
wire  signed [11:0] p_Val2_125_fu_2330_p2;
reg  signed [11:0] p_Val2_125_reg_3930;
wire  signed [11:0] p_Val2_126_fu_2376_p2;
reg  signed [11:0] p_Val2_126_reg_3935;
wire  signed [11:0] p_Val2_127_fu_2422_p2;
reg  signed [11:0] p_Val2_127_reg_3940;
wire  signed [11:0] p_Val2_128_fu_2468_p2;
reg  signed [11:0] p_Val2_128_reg_3945;
wire  signed [11:0] p_Val2_129_fu_2514_p2;
reg  signed [11:0] p_Val2_129_reg_3950;
wire  signed [11:0] p_Val2_130_fu_2560_p2;
reg  signed [11:0] p_Val2_130_reg_3955;
wire  signed [11:0] p_Val2_131_fu_2606_p2;
reg  signed [11:0] p_Val2_131_reg_3960;
wire  signed [11:0] p_Val2_132_fu_2652_p2;
reg  signed [11:0] p_Val2_132_reg_3965;
wire  signed [11:0] p_Val2_133_fu_2698_p2;
reg  signed [11:0] p_Val2_133_reg_3970;
wire  signed [11:0] p_Val2_134_fu_2744_p2;
reg  signed [11:0] p_Val2_134_reg_3975;
wire  signed [11:0] p_Val2_135_fu_2790_p2;
reg  signed [11:0] p_Val2_135_reg_3980;
wire  signed [11:0] p_Val2_136_fu_2836_p2;
reg  signed [11:0] p_Val2_136_reg_3985;
wire  signed [11:0] p_Val2_137_fu_2882_p2;
reg  signed [11:0] p_Val2_137_reg_3990;
wire  signed [11:0] p_Val2_138_fu_2928_p2;
reg  signed [11:0] p_Val2_138_reg_3995;
wire  signed [11:0] p_Val2_139_fu_2974_p2;
reg  signed [11:0] p_Val2_139_reg_4000;
wire   [12:0] tmp43_fu_3234_p2;
reg   [12:0] tmp43_reg_4005;
wire   [12:0] tmp46_fu_3240_p2;
reg   [12:0] tmp46_reg_4010;
wire   [12:0] tmp47_fu_3246_p2;
reg   [12:0] tmp47_reg_4015;
wire   [14:0] tmp2_fu_3462_p2;
reg   [14:0] tmp2_reg_4020;
wire    ap_CS_fsm_state4;
wire   [14:0] tmp13_fu_3552_p2;
reg   [14:0] tmp13_reg_4025;
wire   [14:0] tmp25_fu_3642_p2;
reg   [14:0] tmp25_reg_4030;
wire   [14:0] tmp36_fu_3715_p2;
reg   [14:0] tmp36_reg_4035;
wire    ap_CS_fsm_state5;
wire   [7:0] p_Val2_84_fu_960_p0;
wire  signed [7:0] p_Val2_84_fu_960_p1;
wire   [15:0] p_Val2_84_fu_960_p2;
wire   [7:0] p_Val2_86_fu_992_p0;
wire  signed [7:0] p_Val2_86_fu_992_p1;
wire   [15:0] p_Val2_86_fu_992_p2;
wire   [7:0] p_Val2_88_fu_1024_p0;
wire  signed [7:0] p_Val2_88_fu_1024_p1;
wire   [15:0] p_Val2_88_fu_1024_p2;
wire   [7:0] p_Val2_s_fu_1056_p0;
wire  signed [7:0] p_Val2_s_fu_1056_p1;
wire   [15:0] p_Val2_s_fu_1056_p2;
wire   [10:0] tmp_2_fu_1062_p4;
wire   [0:0] tmp_97_fu_1076_p3;
wire  signed [11:0] p_Val2_1_cast_fu_1072_p1;
wire   [11:0] p_Result_1_cast_fu_1084_p1;
wire   [7:0] p_Val2_2_fu_1102_p0;
wire  signed [7:0] p_Val2_2_fu_1102_p1;
wire   [15:0] p_Val2_2_fu_1102_p2;
wire   [10:0] tmp_6_fu_1108_p4;
wire   [0:0] tmp_98_fu_1122_p3;
wire  signed [11:0] p_Val2_4_cast_fu_1118_p1;
wire   [11:0] p_Result_3_cast_fu_1130_p1;
wire   [7:0] p_Val2_4_fu_1148_p0;
wire  signed [7:0] p_Val2_4_fu_1148_p1;
wire   [15:0] p_Val2_4_fu_1148_p2;
wire   [10:0] tmp_s_fu_1154_p4;
wire   [0:0] tmp_99_fu_1168_p3;
wire  signed [11:0] p_Val2_7_cast_fu_1164_p1;
wire   [11:0] p_Result_5_cast_fu_1176_p1;
wire   [7:0] p_Val2_6_fu_1194_p0;
wire  signed [7:0] p_Val2_6_fu_1194_p1;
wire   [15:0] p_Val2_6_fu_1194_p2;
wire   [10:0] tmp_1_fu_1200_p4;
wire   [0:0] tmp_100_fu_1214_p3;
wire  signed [11:0] p_Val2_10_cast_fu_1210_p1;
wire   [11:0] p_Result_7_cast_fu_1222_p1;
wire   [7:0] p_Val2_8_fu_1240_p0;
wire  signed [7:0] p_Val2_8_fu_1240_p1;
wire   [15:0] p_Val2_8_fu_1240_p2;
wire   [10:0] tmp_7_fu_1246_p4;
wire   [0:0] tmp_101_fu_1260_p3;
wire  signed [11:0] p_Val2_13_cast_fu_1256_p1;
wire   [11:0] p_Result_9_cast_fu_1268_p1;
wire   [7:0] p_Val2_10_fu_1286_p0;
wire  signed [7:0] p_Val2_10_fu_1286_p1;
wire   [15:0] p_Val2_10_fu_1286_p2;
wire   [10:0] tmp_10_fu_1292_p4;
wire   [0:0] tmp_102_fu_1306_p3;
wire  signed [11:0] p_Val2_16_cast_fu_1302_p1;
wire   [11:0] p_Result_10_cast_fu_1314_p1;
wire   [7:0] p_Val2_12_fu_1332_p0;
wire  signed [7:0] p_Val2_12_fu_1332_p1;
wire   [15:0] p_Val2_12_fu_1332_p2;
wire   [10:0] tmp_12_fu_1338_p4;
wire   [0:0] tmp_103_fu_1352_p3;
wire  signed [11:0] p_Val2_19_cast_fu_1348_p1;
wire   [11:0] p_Result_12_cast_fu_1360_p1;
wire   [7:0] p_Val2_14_fu_1378_p0;
wire  signed [7:0] p_Val2_14_fu_1378_p1;
wire   [15:0] p_Val2_14_fu_1378_p2;
wire   [10:0] tmp_14_fu_1384_p4;
wire   [0:0] tmp_104_fu_1398_p3;
wire  signed [11:0] p_Val2_22_cast_fu_1394_p1;
wire   [11:0] p_Result_14_cast_fu_1406_p1;
wire   [7:0] p_Val2_16_fu_1424_p0;
wire  signed [7:0] p_Val2_16_fu_1424_p1;
wire   [15:0] p_Val2_16_fu_1424_p2;
wire   [10:0] tmp_16_fu_1430_p4;
wire   [0:0] tmp_105_fu_1444_p3;
wire  signed [11:0] p_Val2_25_cast_fu_1440_p1;
wire   [11:0] p_Result_16_cast_fu_1452_p1;
wire   [7:0] p_Val2_18_fu_1470_p0;
wire  signed [7:0] p_Val2_18_fu_1470_p1;
wire   [15:0] p_Val2_18_fu_1470_p2;
wire   [10:0] tmp_18_fu_1476_p4;
wire   [0:0] tmp_106_fu_1490_p3;
wire  signed [11:0] p_Val2_28_cast_fu_1486_p1;
wire   [11:0] p_Result_18_cast_fu_1498_p1;
wire   [7:0] p_Val2_20_fu_1516_p0;
wire  signed [7:0] p_Val2_20_fu_1516_p1;
wire   [15:0] p_Val2_20_fu_1516_p2;
wire   [10:0] tmp_20_fu_1522_p4;
wire   [0:0] tmp_107_fu_1536_p3;
wire  signed [11:0] p_Val2_31_cast_fu_1532_p1;
wire   [11:0] p_Result_20_cast_fu_1544_p1;
wire   [7:0] p_Val2_22_fu_1562_p0;
wire  signed [7:0] p_Val2_22_fu_1562_p1;
wire   [15:0] p_Val2_22_fu_1562_p2;
wire   [10:0] tmp_22_fu_1568_p4;
wire   [0:0] tmp_108_fu_1582_p3;
wire  signed [11:0] p_Val2_34_cast_fu_1578_p1;
wire   [11:0] p_Result_22_cast_fu_1590_p1;
wire   [7:0] p_Val2_24_fu_1608_p0;
wire  signed [7:0] p_Val2_24_fu_1608_p1;
wire   [15:0] p_Val2_24_fu_1608_p2;
wire   [10:0] tmp_24_fu_1614_p4;
wire   [0:0] tmp_109_fu_1628_p3;
wire  signed [11:0] p_Val2_37_cast_fu_1624_p1;
wire   [11:0] p_Result_24_cast_fu_1636_p1;
wire   [7:0] p_Val2_26_fu_1654_p0;
wire  signed [7:0] p_Val2_26_fu_1654_p1;
wire   [15:0] p_Val2_26_fu_1654_p2;
wire   [10:0] tmp_26_fu_1660_p4;
wire   [0:0] tmp_110_fu_1674_p3;
wire  signed [11:0] p_Val2_40_cast_fu_1670_p1;
wire   [11:0] p_Result_26_cast_fu_1682_p1;
wire   [7:0] p_Val2_28_fu_1700_p0;
wire  signed [7:0] p_Val2_28_fu_1700_p1;
wire   [15:0] p_Val2_28_fu_1700_p2;
wire   [10:0] tmp_28_fu_1706_p4;
wire   [0:0] tmp_111_fu_1720_p3;
wire  signed [11:0] p_Val2_43_cast_fu_1716_p1;
wire   [11:0] p_Result_28_cast_fu_1728_p1;
wire   [7:0] p_Val2_30_fu_1746_p0;
wire  signed [7:0] p_Val2_30_fu_1746_p1;
wire   [15:0] p_Val2_30_fu_1746_p2;
wire   [10:0] tmp_30_fu_1752_p4;
wire   [0:0] tmp_112_fu_1766_p3;
wire  signed [11:0] p_Val2_46_cast_fu_1762_p1;
wire   [11:0] p_Result_30_cast_fu_1774_p1;
wire   [7:0] p_Val2_32_fu_1792_p0;
wire  signed [7:0] p_Val2_32_fu_1792_p1;
wire   [15:0] p_Val2_32_fu_1792_p2;
wire   [10:0] tmp_32_fu_1798_p4;
wire   [0:0] tmp_113_fu_1812_p3;
wire  signed [11:0] p_Val2_49_cast_fu_1808_p1;
wire   [11:0] p_Result_32_cast_fu_1820_p1;
wire   [7:0] p_Val2_34_fu_1838_p0;
wire  signed [7:0] p_Val2_34_fu_1838_p1;
wire   [15:0] p_Val2_34_fu_1838_p2;
wire   [10:0] tmp_34_fu_1844_p4;
wire   [0:0] tmp_114_fu_1858_p3;
wire  signed [11:0] p_Val2_52_cast_fu_1854_p1;
wire   [11:0] p_Result_34_cast_fu_1866_p1;
wire   [7:0] p_Val2_36_fu_1884_p0;
wire  signed [7:0] p_Val2_36_fu_1884_p1;
wire   [15:0] p_Val2_36_fu_1884_p2;
wire   [10:0] tmp_36_fu_1890_p4;
wire   [0:0] tmp_115_fu_1904_p3;
wire  signed [11:0] p_Val2_55_cast_fu_1900_p1;
wire   [11:0] p_Result_36_cast_fu_1912_p1;
wire   [7:0] p_Val2_38_fu_1930_p0;
wire  signed [7:0] p_Val2_38_fu_1930_p1;
wire   [15:0] p_Val2_38_fu_1930_p2;
wire   [10:0] tmp_38_fu_1936_p4;
wire   [0:0] tmp_116_fu_1950_p3;
wire  signed [11:0] p_Val2_58_cast_fu_1946_p1;
wire   [11:0] p_Result_38_cast_fu_1958_p1;
wire   [7:0] p_Val2_40_fu_1976_p0;
wire  signed [7:0] p_Val2_40_fu_1976_p1;
wire   [15:0] p_Val2_40_fu_1976_p2;
wire   [10:0] tmp_40_fu_1982_p4;
wire   [0:0] tmp_117_fu_1996_p3;
wire  signed [11:0] p_Val2_61_cast_fu_1992_p1;
wire   [11:0] p_Result_40_cast_fu_2004_p1;
wire   [7:0] p_Val2_42_fu_2022_p0;
wire  signed [7:0] p_Val2_42_fu_2022_p1;
wire   [15:0] p_Val2_42_fu_2022_p2;
wire   [10:0] tmp_42_fu_2028_p4;
wire   [0:0] tmp_118_fu_2042_p3;
wire  signed [11:0] p_Val2_64_cast_fu_2038_p1;
wire   [11:0] p_Result_42_cast_fu_2050_p1;
wire   [7:0] p_Val2_44_fu_2068_p0;
wire  signed [7:0] p_Val2_44_fu_2068_p1;
wire   [15:0] p_Val2_44_fu_2068_p2;
wire   [10:0] tmp_44_fu_2074_p4;
wire   [0:0] tmp_119_fu_2088_p3;
wire  signed [11:0] p_Val2_67_cast_fu_2084_p1;
wire   [11:0] p_Result_44_cast_fu_2096_p1;
wire   [7:0] p_Val2_46_fu_2114_p0;
wire  signed [7:0] p_Val2_46_fu_2114_p1;
wire   [15:0] p_Val2_46_fu_2114_p2;
wire   [10:0] tmp_46_fu_2120_p4;
wire   [0:0] tmp_120_fu_2134_p3;
wire  signed [11:0] p_Val2_70_cast_fu_2130_p1;
wire   [11:0] p_Result_46_cast_fu_2142_p1;
wire   [7:0] p_Val2_48_fu_2160_p0;
wire  signed [7:0] p_Val2_48_fu_2160_p1;
wire   [15:0] p_Val2_48_fu_2160_p2;
wire   [10:0] tmp_48_fu_2166_p4;
wire   [0:0] tmp_121_fu_2180_p3;
wire  signed [11:0] p_Val2_73_cast_fu_2176_p1;
wire   [11:0] p_Result_48_cast_fu_2188_p1;
wire   [7:0] p_Val2_50_fu_2206_p0;
wire  signed [7:0] p_Val2_50_fu_2206_p1;
wire   [15:0] p_Val2_50_fu_2206_p2;
wire   [10:0] tmp_50_fu_2212_p4;
wire   [0:0] tmp_122_fu_2226_p3;
wire  signed [11:0] p_Val2_76_cast_fu_2222_p1;
wire   [11:0] p_Result_50_cast_fu_2234_p1;
wire   [7:0] p_Val2_52_fu_2252_p0;
wire  signed [7:0] p_Val2_52_fu_2252_p1;
wire   [15:0] p_Val2_52_fu_2252_p2;
wire   [10:0] tmp_52_fu_2258_p4;
wire   [0:0] tmp_123_fu_2272_p3;
wire  signed [11:0] p_Val2_79_cast_fu_2268_p1;
wire   [11:0] p_Result_52_cast_fu_2280_p1;
wire   [7:0] p_Val2_54_fu_2298_p0;
wire  signed [7:0] p_Val2_54_fu_2298_p1;
wire   [15:0] p_Val2_54_fu_2298_p2;
wire   [10:0] tmp_54_fu_2304_p4;
wire   [0:0] tmp_124_fu_2318_p3;
wire  signed [11:0] p_Val2_82_cast_fu_2314_p1;
wire   [11:0] p_Result_54_cast_fu_2326_p1;
wire   [7:0] p_Val2_56_fu_2344_p0;
wire  signed [7:0] p_Val2_56_fu_2344_p1;
wire   [15:0] p_Val2_56_fu_2344_p2;
wire   [10:0] tmp_56_fu_2350_p4;
wire   [0:0] tmp_125_fu_2364_p3;
wire  signed [11:0] p_Val2_85_cast_fu_2360_p1;
wire   [11:0] p_Result_56_cast_fu_2372_p1;
wire   [7:0] p_Val2_58_fu_2390_p0;
wire  signed [7:0] p_Val2_58_fu_2390_p1;
wire   [15:0] p_Val2_58_fu_2390_p2;
wire   [10:0] tmp_58_fu_2396_p4;
wire   [0:0] tmp_126_fu_2410_p3;
wire  signed [11:0] p_Val2_88_cast_fu_2406_p1;
wire   [11:0] p_Result_58_cast_fu_2418_p1;
wire   [7:0] p_Val2_60_fu_2436_p0;
wire  signed [7:0] p_Val2_60_fu_2436_p1;
wire   [15:0] p_Val2_60_fu_2436_p2;
wire   [10:0] tmp_60_fu_2442_p4;
wire   [0:0] tmp_127_fu_2456_p3;
wire  signed [11:0] p_Val2_91_cast_fu_2452_p1;
wire   [11:0] p_Result_60_cast_fu_2464_p1;
wire   [7:0] p_Val2_62_fu_2482_p0;
wire  signed [7:0] p_Val2_62_fu_2482_p1;
wire   [15:0] p_Val2_62_fu_2482_p2;
wire   [10:0] tmp_62_fu_2488_p4;
wire   [0:0] tmp_128_fu_2502_p3;
wire  signed [11:0] p_Val2_94_cast_fu_2498_p1;
wire   [11:0] p_Result_62_cast_fu_2510_p1;
wire   [7:0] p_Val2_64_fu_2528_p0;
wire  signed [7:0] p_Val2_64_fu_2528_p1;
wire   [15:0] p_Val2_64_fu_2528_p2;
wire   [10:0] tmp_64_fu_2534_p4;
wire   [0:0] tmp_129_fu_2548_p3;
wire  signed [11:0] p_Val2_97_cast_fu_2544_p1;
wire   [11:0] p_Result_64_cast_fu_2556_p1;
wire   [7:0] p_Val2_66_fu_2574_p0;
wire  signed [7:0] p_Val2_66_fu_2574_p1;
wire   [15:0] p_Val2_66_fu_2574_p2;
wire   [10:0] tmp_66_fu_2580_p4;
wire   [0:0] tmp_130_fu_2594_p3;
wire  signed [11:0] p_Val2_100_cast_fu_2590_p1;
wire   [11:0] p_Result_66_cast_fu_2602_p1;
wire   [7:0] p_Val2_68_fu_2620_p0;
wire  signed [7:0] p_Val2_68_fu_2620_p1;
wire   [15:0] p_Val2_68_fu_2620_p2;
wire   [10:0] tmp_68_fu_2626_p4;
wire   [0:0] tmp_131_fu_2640_p3;
wire  signed [11:0] p_Val2_103_cast_fu_2636_p1;
wire   [11:0] p_Result_68_cast_fu_2648_p1;
wire   [7:0] p_Val2_70_fu_2666_p0;
wire  signed [7:0] p_Val2_70_fu_2666_p1;
wire   [15:0] p_Val2_70_fu_2666_p2;
wire   [10:0] tmp_70_fu_2672_p4;
wire   [0:0] tmp_132_fu_2686_p3;
wire  signed [11:0] p_Val2_106_cast_fu_2682_p1;
wire   [11:0] p_Result_70_cast_fu_2694_p1;
wire   [7:0] p_Val2_72_fu_2712_p0;
wire  signed [7:0] p_Val2_72_fu_2712_p1;
wire   [15:0] p_Val2_72_fu_2712_p2;
wire   [10:0] tmp_72_fu_2718_p4;
wire   [0:0] tmp_133_fu_2732_p3;
wire  signed [11:0] p_Val2_109_cast_fu_2728_p1;
wire   [11:0] p_Result_72_cast_fu_2740_p1;
wire   [7:0] p_Val2_74_fu_2758_p0;
wire  signed [7:0] p_Val2_74_fu_2758_p1;
wire   [15:0] p_Val2_74_fu_2758_p2;
wire   [10:0] tmp_74_fu_2764_p4;
wire   [0:0] tmp_134_fu_2778_p3;
wire  signed [11:0] p_Val2_112_cast_fu_2774_p1;
wire   [11:0] p_Result_74_cast_fu_2786_p1;
wire   [7:0] p_Val2_76_fu_2804_p0;
wire  signed [7:0] p_Val2_76_fu_2804_p1;
wire   [15:0] p_Val2_76_fu_2804_p2;
wire   [10:0] tmp_76_fu_2810_p4;
wire   [0:0] tmp_135_fu_2824_p3;
wire  signed [11:0] p_Val2_115_cast_fu_2820_p1;
wire   [11:0] p_Result_76_cast_fu_2832_p1;
wire   [7:0] p_Val2_78_fu_2850_p0;
wire  signed [7:0] p_Val2_78_fu_2850_p1;
wire   [15:0] p_Val2_78_fu_2850_p2;
wire   [10:0] tmp_78_fu_2856_p4;
wire   [0:0] tmp_136_fu_2870_p3;
wire  signed [11:0] p_Val2_118_cast_fu_2866_p1;
wire   [11:0] p_Result_78_cast_fu_2878_p1;
wire   [7:0] p_Val2_80_fu_2896_p0;
wire  signed [7:0] p_Val2_80_fu_2896_p1;
wire   [15:0] p_Val2_80_fu_2896_p2;
wire   [10:0] tmp_80_fu_2902_p4;
wire   [0:0] tmp_137_fu_2916_p3;
wire  signed [11:0] p_Val2_121_cast_fu_2912_p1;
wire   [11:0] p_Result_80_cast_fu_2924_p1;
wire   [7:0] p_Val2_82_fu_2942_p0;
wire  signed [7:0] p_Val2_82_fu_2942_p1;
wire   [15:0] p_Val2_82_fu_2942_p2;
wire   [10:0] tmp_82_fu_2948_p4;
wire   [0:0] tmp_138_fu_2962_p3;
wire  signed [11:0] p_Val2_124_cast_fu_2958_p1;
wire   [11:0] p_Result_82_cast_fu_2970_p1;
wire  signed [11:0] p_Val2_126_cast_fu_2980_p1;
wire   [11:0] p_Result_84_cast_fu_2983_p1;
wire  signed [11:0] p_Val2_140_fu_2986_p2;
wire  signed [11:0] p_Val2_128_cast_fu_2996_p1;
wire   [11:0] p_Result_86_cast_fu_2999_p1;
wire  signed [11:0] p_Val2_141_fu_3002_p2;
wire  signed [11:0] p_Val2_130_cast_fu_3012_p1;
wire   [11:0] p_Result_88_cast_fu_3015_p1;
wire  signed [11:0] p_Val2_142_fu_3018_p2;
wire   [7:0] p_Val2_90_fu_3036_p0;
wire  signed [7:0] p_Val2_90_fu_3036_p1;
wire   [15:0] p_Val2_90_fu_3036_p2;
wire   [10:0] tmp_90_fu_3042_p4;
wire   [0:0] tmp_142_fu_3056_p3;
wire  signed [11:0] p_Val2_132_cast_fu_3052_p1;
wire   [11:0] p_Result_90_cast_fu_3064_p1;
wire  signed [11:0] p_Val2_143_fu_3068_p2;
wire   [7:0] p_Val2_92_fu_3086_p0;
wire  signed [7:0] p_Val2_92_fu_3086_p1;
wire   [15:0] p_Val2_92_fu_3086_p2;
wire   [10:0] tmp_92_fu_3092_p4;
wire   [0:0] tmp_143_fu_3106_p3;
wire  signed [11:0] p_Val2_134_cast_fu_3102_p1;
wire   [11:0] p_Result_92_cast_fu_3114_p1;
wire  signed [11:0] p_Val2_144_fu_3118_p2;
wire   [7:0] p_Val2_94_fu_3136_p0;
wire  signed [7:0] p_Val2_94_fu_3136_p1;
wire   [15:0] p_Val2_94_fu_3136_p2;
wire   [10:0] tmp_94_fu_3142_p4;
wire   [0:0] tmp_144_fu_3156_p3;
wire  signed [11:0] p_Val2_136_cast_fu_3152_p1;
wire   [11:0] p_Result_94_cast_fu_3164_p1;
wire  signed [11:0] p_Val2_145_fu_3168_p2;
wire   [7:0] p_Val2_96_fu_3186_p0;
wire  signed [7:0] p_Val2_96_fu_3186_p1;
wire   [15:0] p_Val2_96_fu_3186_p2;
wire   [10:0] tmp_96_fu_3192_p4;
wire   [0:0] tmp_145_fu_3206_p3;
wire  signed [11:0] p_Val2_138_cast_fu_3202_p1;
wire   [11:0] p_Result_96_cast_fu_3214_p1;
wire  signed [11:0] p_Val2_146_fu_3218_p2;
wire  signed [12:0] p_Val2_231_cast_fu_3008_p1;
wire  signed [12:0] p_Val2_232_cast_fu_3024_p1;
wire   [12:0] tmp44_fu_3228_p2;
wire  signed [12:0] p_Val2_230_cast_fu_2992_p1;
wire  signed [12:0] p_Val2_233_cast_fu_3074_p1;
wire  signed [12:0] p_Val2_234_cast_fu_3124_p1;
wire  signed [12:0] p_Val2_235_cast_fu_3174_p1;
wire  signed [12:0] p_Val2_236_cast_fu_3224_p1;
wire  signed [12:0] p_Val2_188_cast_fu_3252_p1;
wire  signed [12:0] p_Val2_190_cast_fu_3258_p1;
wire   [12:0] tmp5_fu_3378_p2;
wire  signed [12:0] p_Val2_189_cast_fu_3255_p1;
wire   [12:0] tmp4_fu_3384_p2;
wire  signed [12:0] p_Val2_192_cast_fu_3264_p1;
wire  signed [12:0] p_Val2_193_cast_fu_3267_p1;
wire   [12:0] tmp7_fu_3394_p2;
wire  signed [12:0] p_Val2_191_cast_fu_3261_p1;
wire   [12:0] tmp6_fu_3400_p2;
wire  signed [13:0] tmp6_cast_fu_3406_p1;
wire  signed [13:0] tmp4_cast_fu_3390_p1;
wire   [13:0] tmp3_fu_3410_p2;
wire  signed [12:0] p_Val2_195_cast_fu_3273_p1;
wire  signed [12:0] p_Val2_196_cast_fu_3276_p1;
wire   [12:0] tmp10_fu_3420_p2;
wire  signed [12:0] p_Val2_194_cast_fu_3270_p1;
wire   [12:0] tmp9_fu_3426_p2;
wire  signed [12:0] p_Val2_198_cast_fu_3282_p1;
wire  signed [12:0] p_Val2_199_cast_fu_3285_p1;
wire   [12:0] tmp12_fu_3436_p2;
wire  signed [12:0] p_Val2_197_cast_fu_3279_p1;
wire   [12:0] tmp11_fu_3442_p2;
wire  signed [13:0] tmp11_cast_fu_3448_p1;
wire  signed [13:0] tmp9_cast_fu_3432_p1;
wire   [13:0] tmp8_fu_3452_p2;
wire  signed [14:0] tmp8_cast_fu_3458_p1;
wire  signed [14:0] tmp3_cast_fu_3416_p1;
wire  signed [12:0] p_Val2_201_cast_fu_3291_p1;
wire  signed [12:0] p_Val2_202_cast_fu_3294_p1;
wire   [12:0] tmp16_fu_3468_p2;
wire  signed [12:0] p_Val2_200_cast_fu_3288_p1;
wire   [12:0] tmp15_fu_3474_p2;
wire  signed [12:0] p_Val2_204_cast_fu_3300_p1;
wire  signed [12:0] p_Val2_205_cast_fu_3303_p1;
wire   [12:0] tmp18_fu_3484_p2;
wire  signed [12:0] p_Val2_203_cast_fu_3297_p1;
wire   [12:0] tmp17_fu_3490_p2;
wire  signed [13:0] tmp17_cast_fu_3496_p1;
wire  signed [13:0] tmp15_cast_fu_3480_p1;
wire   [13:0] tmp14_fu_3500_p2;
wire  signed [12:0] p_Val2_207_cast_fu_3309_p1;
wire  signed [12:0] p_Val2_208_cast_fu_3312_p1;
wire   [12:0] tmp21_fu_3510_p2;
wire  signed [12:0] p_Val2_206_cast_fu_3306_p1;
wire   [12:0] tmp20_fu_3516_p2;
wire  signed [12:0] p_Val2_210_cast_fu_3318_p1;
wire  signed [12:0] p_Val2_211_cast_fu_3321_p1;
wire   [12:0] tmp23_fu_3526_p2;
wire  signed [12:0] p_Val2_209_cast_fu_3315_p1;
wire   [12:0] tmp22_fu_3532_p2;
wire  signed [13:0] tmp22_cast_fu_3538_p1;
wire  signed [13:0] tmp20_cast_fu_3522_p1;
wire   [13:0] tmp19_fu_3542_p2;
wire  signed [14:0] tmp19_cast_fu_3548_p1;
wire  signed [14:0] tmp14_cast_fu_3506_p1;
wire  signed [12:0] p_Val2_213_cast_fu_3327_p1;
wire  signed [12:0] p_Val2_214_cast_fu_3330_p1;
wire   [12:0] tmp28_fu_3558_p2;
wire  signed [12:0] p_Val2_212_cast_fu_3324_p1;
wire   [12:0] tmp27_fu_3564_p2;
wire  signed [12:0] p_Val2_216_cast_fu_3336_p1;
wire  signed [12:0] p_Val2_217_cast_fu_3339_p1;
wire   [12:0] tmp30_fu_3574_p2;
wire  signed [12:0] p_Val2_215_cast_fu_3333_p1;
wire   [12:0] tmp29_fu_3580_p2;
wire  signed [13:0] tmp29_cast_fu_3586_p1;
wire  signed [13:0] tmp27_cast_fu_3570_p1;
wire   [13:0] tmp26_fu_3590_p2;
wire  signed [12:0] p_Val2_219_cast_fu_3345_p1;
wire  signed [12:0] p_Val2_220_cast_fu_3348_p1;
wire   [12:0] tmp33_fu_3600_p2;
wire  signed [12:0] p_Val2_218_cast_fu_3342_p1;
wire   [12:0] tmp32_fu_3606_p2;
wire  signed [12:0] p_Val2_222_cast_fu_3354_p1;
wire  signed [12:0] p_Val2_223_cast_fu_3357_p1;
wire   [12:0] tmp35_fu_3616_p2;
wire  signed [12:0] p_Val2_221_cast_fu_3351_p1;
wire   [12:0] tmp34_fu_3622_p2;
wire  signed [13:0] tmp34_cast_fu_3628_p1;
wire  signed [13:0] tmp32_cast_fu_3612_p1;
wire   [13:0] tmp31_fu_3632_p2;
wire  signed [14:0] tmp31_cast_fu_3638_p1;
wire  signed [14:0] tmp26_cast_fu_3596_p1;
wire  signed [12:0] p_Val2_225_cast_fu_3363_p1;
wire  signed [12:0] p_Val2_226_cast_fu_3366_p1;
wire   [12:0] tmp39_fu_3648_p2;
wire  signed [12:0] p_Val2_224_cast_fu_3360_p1;
wire   [12:0] tmp38_fu_3654_p2;
wire  signed [12:0] p_Val2_228_cast_fu_3372_p1;
wire  signed [12:0] p_Val2_229_cast_fu_3375_p1;
wire   [12:0] tmp41_fu_3664_p2;
wire  signed [12:0] p_Val2_227_cast_fu_3369_p1;
wire   [12:0] tmp40_fu_3670_p2;
wire  signed [13:0] tmp40_cast_fu_3676_p1;
wire  signed [13:0] tmp38_cast_fu_3660_p1;
wire   [13:0] tmp37_fu_3680_p2;
wire  signed [13:0] tmp47_cast_fu_3696_p1;
wire  signed [13:0] tmp46_cast_fu_3693_p1;
wire   [13:0] tmp45_fu_3699_p2;
wire  signed [13:0] tmp43_cast_fu_3690_p1;
wire   [13:0] tmp42_fu_3705_p2;
wire  signed [14:0] tmp42_cast_fu_3711_p1;
wire  signed [14:0] tmp37_cast_fu_3686_p1;
wire  signed [15:0] tmp13_cast_fu_3724_p1;
wire  signed [15:0] tmp2_cast_fu_3721_p1;
wire  signed [15:0] tmp36_cast_fu_3736_p1;
wire  signed [15:0] tmp25_cast_fu_3733_p1;
wire   [15:0] tmp24_fu_3739_p2;
wire   [15:0] tmp1_fu_3727_p2;
wire   [0:0] storemerge1_fu_3751_p0;
wire   [15:0] p_Val2_191_6_fu_3745_p2;
reg   [4:0] ap_NS_fsm;
wire   [15:0] p_Val2_10_fu_1286_p00;
wire   [15:0] p_Val2_12_fu_1332_p00;
wire   [15:0] p_Val2_14_fu_1378_p00;
wire   [15:0] p_Val2_16_fu_1424_p00;
wire   [15:0] p_Val2_18_fu_1470_p00;
wire   [15:0] p_Val2_20_fu_1516_p00;
wire   [15:0] p_Val2_22_fu_1562_p00;
wire   [15:0] p_Val2_24_fu_1608_p00;
wire   [15:0] p_Val2_26_fu_1654_p00;
wire   [15:0] p_Val2_28_fu_1700_p00;
wire   [15:0] p_Val2_2_fu_1102_p00;
wire   [15:0] p_Val2_30_fu_1746_p00;
wire   [15:0] p_Val2_32_fu_1792_p00;
wire   [15:0] p_Val2_34_fu_1838_p00;
wire   [15:0] p_Val2_36_fu_1884_p00;
wire   [15:0] p_Val2_38_fu_1930_p00;
wire   [15:0] p_Val2_40_fu_1976_p00;
wire   [15:0] p_Val2_42_fu_2022_p00;
wire   [15:0] p_Val2_44_fu_2068_p00;
wire   [15:0] p_Val2_46_fu_2114_p00;
wire   [15:0] p_Val2_48_fu_2160_p00;
wire   [15:0] p_Val2_4_fu_1148_p00;
wire   [15:0] p_Val2_50_fu_2206_p00;
wire   [15:0] p_Val2_52_fu_2252_p00;
wire   [15:0] p_Val2_54_fu_2298_p00;
wire   [15:0] p_Val2_56_fu_2344_p00;
wire   [15:0] p_Val2_58_fu_2390_p00;
wire   [15:0] p_Val2_60_fu_2436_p00;
wire   [15:0] p_Val2_62_fu_2482_p00;
wire   [15:0] p_Val2_64_fu_2528_p00;
wire   [15:0] p_Val2_66_fu_2574_p00;
wire   [15:0] p_Val2_68_fu_2620_p00;
wire   [15:0] p_Val2_6_fu_1194_p00;
wire   [15:0] p_Val2_70_fu_2666_p00;
wire   [15:0] p_Val2_72_fu_2712_p00;
wire   [15:0] p_Val2_74_fu_2758_p00;
wire   [15:0] p_Val2_76_fu_2804_p00;
wire   [15:0] p_Val2_78_fu_2850_p00;
wire   [15:0] p_Val2_80_fu_2896_p00;
wire   [15:0] p_Val2_82_fu_2942_p00;
wire   [15:0] p_Val2_84_fu_960_p00;
wire   [15:0] p_Val2_86_fu_992_p00;
wire   [15:0] p_Val2_88_fu_1024_p00;
wire   [15:0] p_Val2_8_fu_1240_p00;
wire   [15:0] p_Val2_90_fu_3036_p00;
wire   [15:0] p_Val2_92_fu_3086_p00;
wire   [15:0] p_Val2_94_fu_3136_p00;
wire   [15:0] p_Val2_96_fu_3186_p00;
wire   [15:0] p_Val2_s_fu_1056_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (sop_enable_read_read_fu_344_p2 == 1'd1))) begin
        p_Val2_100_reg_3805 <= p_Val2_100_fu_1180_p2;
        p_Val2_101_reg_3810 <= p_Val2_101_fu_1226_p2;
        p_Val2_102_reg_3815 <= p_Val2_102_fu_1272_p2;
        p_Val2_103_reg_3820 <= p_Val2_103_fu_1318_p2;
        p_Val2_104_reg_3825 <= p_Val2_104_fu_1364_p2;
        p_Val2_105_reg_3830 <= p_Val2_105_fu_1410_p2;
        p_Val2_106_reg_3835 <= p_Val2_106_fu_1456_p2;
        p_Val2_107_reg_3840 <= p_Val2_107_fu_1502_p2;
        p_Val2_108_reg_3845 <= p_Val2_108_fu_1548_p2;
        p_Val2_109_reg_3850 <= p_Val2_109_fu_1594_p2;
        p_Val2_110_reg_3855 <= p_Val2_110_fu_1640_p2;
        p_Val2_111_reg_3860 <= p_Val2_111_fu_1686_p2;
        p_Val2_112_reg_3865 <= p_Val2_112_fu_1732_p2;
        p_Val2_113_reg_3870 <= p_Val2_113_fu_1778_p2;
        p_Val2_114_reg_3875 <= p_Val2_114_fu_1824_p2;
        p_Val2_115_reg_3880 <= p_Val2_115_fu_1870_p2;
        p_Val2_116_reg_3885 <= p_Val2_116_fu_1916_p2;
        p_Val2_117_reg_3890 <= p_Val2_117_fu_1962_p2;
        p_Val2_118_reg_3895 <= p_Val2_118_fu_2008_p2;
        p_Val2_119_reg_3900 <= p_Val2_119_fu_2054_p2;
        p_Val2_120_reg_3905 <= p_Val2_120_fu_2100_p2;
        p_Val2_121_reg_3910 <= p_Val2_121_fu_2146_p2;
        p_Val2_122_reg_3915 <= p_Val2_122_fu_2192_p2;
        p_Val2_123_reg_3920 <= p_Val2_123_fu_2238_p2;
        p_Val2_124_reg_3925 <= p_Val2_124_fu_2284_p2;
        p_Val2_125_reg_3930 <= p_Val2_125_fu_2330_p2;
        p_Val2_126_reg_3935 <= p_Val2_126_fu_2376_p2;
        p_Val2_127_reg_3940 <= p_Val2_127_fu_2422_p2;
        p_Val2_128_reg_3945 <= p_Val2_128_fu_2468_p2;
        p_Val2_129_reg_3950 <= p_Val2_129_fu_2514_p2;
        p_Val2_130_reg_3955 <= p_Val2_130_fu_2560_p2;
        p_Val2_131_reg_3960 <= p_Val2_131_fu_2606_p2;
        p_Val2_132_reg_3965 <= p_Val2_132_fu_2652_p2;
        p_Val2_133_reg_3970 <= p_Val2_133_fu_2698_p2;
        p_Val2_134_reg_3975 <= p_Val2_134_fu_2744_p2;
        p_Val2_135_reg_3980 <= p_Val2_135_fu_2790_p2;
        p_Val2_136_reg_3985 <= p_Val2_136_fu_2836_p2;
        p_Val2_137_reg_3990 <= p_Val2_137_fu_2882_p2;
        p_Val2_138_reg_3995 <= p_Val2_138_fu_2928_p2;
        p_Val2_139_reg_4000 <= p_Val2_139_fu_2974_p2;
        p_Val2_98_reg_3795 <= p_Val2_98_fu_1088_p2;
        p_Val2_99_reg_3800 <= p_Val2_99_fu_1134_p2;
        tmp43_reg_4005 <= tmp43_fu_3234_p2;
        tmp46_reg_4010 <= tmp46_fu_3240_p2;
        tmp47_reg_4015 <= tmp47_fu_3246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (sop_enable_read_read_fu_344_p2 == 1'd1))) begin
        tmp13_reg_4025 <= tmp13_fu_3552_p2;
        tmp25_reg_4030 <= tmp25_fu_3642_p2;
        tmp2_reg_4020 <= tmp2_fu_3462_p2;
        tmp36_reg_4035 <= tmp36_fu_3715_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (sop_enable_read_read_fu_344_p2 == 1'd1))) begin
        tmp_139_reg_3770 <= p_Val2_84_fu_960_p2[32'd4];
        tmp_140_reg_3780 <= p_Val2_86_fu_992_p2[32'd4];
        tmp_141_reg_3790 <= p_Val2_88_fu_1024_p2[32'd4];
        tmp_84_reg_3765 <= {{p_Val2_84_fu_960_p2[15:5]}};
        tmp_86_reg_3775 <= {{p_Val2_86_fu_992_p2[15:5]}};
        tmp_88_reg_3785 <= {{p_Val2_88_fu_1024_p2[15:5]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_val_V_ap_vld = 1'b1;
    end else begin
        out_val_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_valid_ap_vld = 1'b1;
    end else begin
        out_valid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign out_val_V = ((storemerge1_fu_3751_p0[0:0] === 1'b1) ? p_Val2_191_6_fu_3745_p2 : 16'd0);

assign out_valid = sop_enable;

assign p_Result_10_cast_fu_1314_p1 = tmp_102_fu_1306_p3;

assign p_Result_12_cast_fu_1360_p1 = tmp_103_fu_1352_p3;

assign p_Result_14_cast_fu_1406_p1 = tmp_104_fu_1398_p3;

assign p_Result_16_cast_fu_1452_p1 = tmp_105_fu_1444_p3;

assign p_Result_18_cast_fu_1498_p1 = tmp_106_fu_1490_p3;

assign p_Result_1_cast_fu_1084_p1 = tmp_97_fu_1076_p3;

assign p_Result_20_cast_fu_1544_p1 = tmp_107_fu_1536_p3;

assign p_Result_22_cast_fu_1590_p1 = tmp_108_fu_1582_p3;

assign p_Result_24_cast_fu_1636_p1 = tmp_109_fu_1628_p3;

assign p_Result_26_cast_fu_1682_p1 = tmp_110_fu_1674_p3;

assign p_Result_28_cast_fu_1728_p1 = tmp_111_fu_1720_p3;

assign p_Result_30_cast_fu_1774_p1 = tmp_112_fu_1766_p3;

assign p_Result_32_cast_fu_1820_p1 = tmp_113_fu_1812_p3;

assign p_Result_34_cast_fu_1866_p1 = tmp_114_fu_1858_p3;

assign p_Result_36_cast_fu_1912_p1 = tmp_115_fu_1904_p3;

assign p_Result_38_cast_fu_1958_p1 = tmp_116_fu_1950_p3;

assign p_Result_3_cast_fu_1130_p1 = tmp_98_fu_1122_p3;

assign p_Result_40_cast_fu_2004_p1 = tmp_117_fu_1996_p3;

assign p_Result_42_cast_fu_2050_p1 = tmp_118_fu_2042_p3;

assign p_Result_44_cast_fu_2096_p1 = tmp_119_fu_2088_p3;

assign p_Result_46_cast_fu_2142_p1 = tmp_120_fu_2134_p3;

assign p_Result_48_cast_fu_2188_p1 = tmp_121_fu_2180_p3;

assign p_Result_50_cast_fu_2234_p1 = tmp_122_fu_2226_p3;

assign p_Result_52_cast_fu_2280_p1 = tmp_123_fu_2272_p3;

assign p_Result_54_cast_fu_2326_p1 = tmp_124_fu_2318_p3;

assign p_Result_56_cast_fu_2372_p1 = tmp_125_fu_2364_p3;

assign p_Result_58_cast_fu_2418_p1 = tmp_126_fu_2410_p3;

assign p_Result_5_cast_fu_1176_p1 = tmp_99_fu_1168_p3;

assign p_Result_60_cast_fu_2464_p1 = tmp_127_fu_2456_p3;

assign p_Result_62_cast_fu_2510_p1 = tmp_128_fu_2502_p3;

assign p_Result_64_cast_fu_2556_p1 = tmp_129_fu_2548_p3;

assign p_Result_66_cast_fu_2602_p1 = tmp_130_fu_2594_p3;

assign p_Result_68_cast_fu_2648_p1 = tmp_131_fu_2640_p3;

assign p_Result_70_cast_fu_2694_p1 = tmp_132_fu_2686_p3;

assign p_Result_72_cast_fu_2740_p1 = tmp_133_fu_2732_p3;

assign p_Result_74_cast_fu_2786_p1 = tmp_134_fu_2778_p3;

assign p_Result_76_cast_fu_2832_p1 = tmp_135_fu_2824_p3;

assign p_Result_78_cast_fu_2878_p1 = tmp_136_fu_2870_p3;

assign p_Result_7_cast_fu_1222_p1 = tmp_100_fu_1214_p3;

assign p_Result_80_cast_fu_2924_p1 = tmp_137_fu_2916_p3;

assign p_Result_82_cast_fu_2970_p1 = tmp_138_fu_2962_p3;

assign p_Result_84_cast_fu_2983_p1 = tmp_139_reg_3770;

assign p_Result_86_cast_fu_2999_p1 = tmp_140_reg_3780;

assign p_Result_88_cast_fu_3015_p1 = tmp_141_reg_3790;

assign p_Result_90_cast_fu_3064_p1 = tmp_142_fu_3056_p3;

assign p_Result_92_cast_fu_3114_p1 = tmp_143_fu_3106_p3;

assign p_Result_94_cast_fu_3164_p1 = tmp_144_fu_3156_p3;

assign p_Result_96_cast_fu_3214_p1 = tmp_145_fu_3206_p3;

assign p_Result_9_cast_fu_1268_p1 = tmp_101_fu_1260_p3;

assign p_Val2_100_cast_fu_2590_p1 = $signed(tmp_66_fu_2580_p4);

assign p_Val2_100_fu_1180_p2 = ($signed(p_Val2_7_cast_fu_1164_p1) + $signed(p_Result_5_cast_fu_1176_p1));

assign p_Val2_101_fu_1226_p2 = ($signed(p_Val2_10_cast_fu_1210_p1) + $signed(p_Result_7_cast_fu_1222_p1));

assign p_Val2_102_fu_1272_p2 = ($signed(p_Val2_13_cast_fu_1256_p1) + $signed(p_Result_9_cast_fu_1268_p1));

assign p_Val2_103_cast_fu_2636_p1 = $signed(tmp_68_fu_2626_p4);

assign p_Val2_103_fu_1318_p2 = ($signed(p_Val2_16_cast_fu_1302_p1) + $signed(p_Result_10_cast_fu_1314_p1));

assign p_Val2_104_fu_1364_p2 = ($signed(p_Val2_19_cast_fu_1348_p1) + $signed(p_Result_12_cast_fu_1360_p1));

assign p_Val2_105_fu_1410_p2 = ($signed(p_Val2_22_cast_fu_1394_p1) + $signed(p_Result_14_cast_fu_1406_p1));

assign p_Val2_106_cast_fu_2682_p1 = $signed(tmp_70_fu_2672_p4);

assign p_Val2_106_fu_1456_p2 = ($signed(p_Val2_25_cast_fu_1440_p1) + $signed(p_Result_16_cast_fu_1452_p1));

assign p_Val2_107_fu_1502_p2 = ($signed(p_Val2_28_cast_fu_1486_p1) + $signed(p_Result_18_cast_fu_1498_p1));

assign p_Val2_108_fu_1548_p2 = ($signed(p_Val2_31_cast_fu_1532_p1) + $signed(p_Result_20_cast_fu_1544_p1));

assign p_Val2_109_cast_fu_2728_p1 = $signed(tmp_72_fu_2718_p4);

assign p_Val2_109_fu_1594_p2 = ($signed(p_Val2_34_cast_fu_1578_p1) + $signed(p_Result_22_cast_fu_1590_p1));

assign p_Val2_10_cast_fu_1210_p1 = $signed(tmp_1_fu_1200_p4);

assign p_Val2_10_fu_1286_p0 = p_Val2_10_fu_1286_p00;

assign p_Val2_10_fu_1286_p00 = pixel_window_5_V;

assign p_Val2_10_fu_1286_p1 = kernel_patch_5_V;

assign p_Val2_10_fu_1286_p2 = ($signed({{1'b0}, {p_Val2_10_fu_1286_p0}}) * $signed(p_Val2_10_fu_1286_p1));

assign p_Val2_110_fu_1640_p2 = ($signed(p_Val2_37_cast_fu_1624_p1) + $signed(p_Result_24_cast_fu_1636_p1));

assign p_Val2_111_fu_1686_p2 = ($signed(p_Val2_40_cast_fu_1670_p1) + $signed(p_Result_26_cast_fu_1682_p1));

assign p_Val2_112_cast_fu_2774_p1 = $signed(tmp_74_fu_2764_p4);

assign p_Val2_112_fu_1732_p2 = ($signed(p_Val2_43_cast_fu_1716_p1) + $signed(p_Result_28_cast_fu_1728_p1));

assign p_Val2_113_fu_1778_p2 = ($signed(p_Val2_46_cast_fu_1762_p1) + $signed(p_Result_30_cast_fu_1774_p1));

assign p_Val2_114_fu_1824_p2 = ($signed(p_Val2_49_cast_fu_1808_p1) + $signed(p_Result_32_cast_fu_1820_p1));

assign p_Val2_115_cast_fu_2820_p1 = $signed(tmp_76_fu_2810_p4);

assign p_Val2_115_fu_1870_p2 = ($signed(p_Val2_52_cast_fu_1854_p1) + $signed(p_Result_34_cast_fu_1866_p1));

assign p_Val2_116_fu_1916_p2 = ($signed(p_Val2_55_cast_fu_1900_p1) + $signed(p_Result_36_cast_fu_1912_p1));

assign p_Val2_117_fu_1962_p2 = ($signed(p_Val2_58_cast_fu_1946_p1) + $signed(p_Result_38_cast_fu_1958_p1));

assign p_Val2_118_cast_fu_2866_p1 = $signed(tmp_78_fu_2856_p4);

assign p_Val2_118_fu_2008_p2 = ($signed(p_Val2_61_cast_fu_1992_p1) + $signed(p_Result_40_cast_fu_2004_p1));

assign p_Val2_119_fu_2054_p2 = ($signed(p_Val2_64_cast_fu_2038_p1) + $signed(p_Result_42_cast_fu_2050_p1));

assign p_Val2_120_fu_2100_p2 = ($signed(p_Val2_67_cast_fu_2084_p1) + $signed(p_Result_44_cast_fu_2096_p1));

assign p_Val2_121_cast_fu_2912_p1 = $signed(tmp_80_fu_2902_p4);

assign p_Val2_121_fu_2146_p2 = ($signed(p_Val2_70_cast_fu_2130_p1) + $signed(p_Result_46_cast_fu_2142_p1));

assign p_Val2_122_fu_2192_p2 = ($signed(p_Val2_73_cast_fu_2176_p1) + $signed(p_Result_48_cast_fu_2188_p1));

assign p_Val2_123_fu_2238_p2 = ($signed(p_Val2_76_cast_fu_2222_p1) + $signed(p_Result_50_cast_fu_2234_p1));

assign p_Val2_124_cast_fu_2958_p1 = $signed(tmp_82_fu_2948_p4);

assign p_Val2_124_fu_2284_p2 = ($signed(p_Val2_79_cast_fu_2268_p1) + $signed(p_Result_52_cast_fu_2280_p1));

assign p_Val2_125_fu_2330_p2 = ($signed(p_Val2_82_cast_fu_2314_p1) + $signed(p_Result_54_cast_fu_2326_p1));

assign p_Val2_126_cast_fu_2980_p1 = $signed(tmp_84_reg_3765);

assign p_Val2_126_fu_2376_p2 = ($signed(p_Val2_85_cast_fu_2360_p1) + $signed(p_Result_56_cast_fu_2372_p1));

assign p_Val2_127_fu_2422_p2 = ($signed(p_Val2_88_cast_fu_2406_p1) + $signed(p_Result_58_cast_fu_2418_p1));

assign p_Val2_128_cast_fu_2996_p1 = $signed(tmp_86_reg_3775);

assign p_Val2_128_fu_2468_p2 = ($signed(p_Val2_91_cast_fu_2452_p1) + $signed(p_Result_60_cast_fu_2464_p1));

assign p_Val2_129_fu_2514_p2 = ($signed(p_Val2_94_cast_fu_2498_p1) + $signed(p_Result_62_cast_fu_2510_p1));

assign p_Val2_12_fu_1332_p0 = p_Val2_12_fu_1332_p00;

assign p_Val2_12_fu_1332_p00 = pixel_window_6_V;

assign p_Val2_12_fu_1332_p1 = kernel_patch_6_V;

assign p_Val2_12_fu_1332_p2 = ($signed({{1'b0}, {p_Val2_12_fu_1332_p0}}) * $signed(p_Val2_12_fu_1332_p1));

assign p_Val2_130_cast_fu_3012_p1 = $signed(tmp_88_reg_3785);

assign p_Val2_130_fu_2560_p2 = ($signed(p_Val2_97_cast_fu_2544_p1) + $signed(p_Result_64_cast_fu_2556_p1));

assign p_Val2_131_fu_2606_p2 = ($signed(p_Val2_100_cast_fu_2590_p1) + $signed(p_Result_66_cast_fu_2602_p1));

assign p_Val2_132_cast_fu_3052_p1 = $signed(tmp_90_fu_3042_p4);

assign p_Val2_132_fu_2652_p2 = ($signed(p_Val2_103_cast_fu_2636_p1) + $signed(p_Result_68_cast_fu_2648_p1));

assign p_Val2_133_fu_2698_p2 = ($signed(p_Val2_106_cast_fu_2682_p1) + $signed(p_Result_70_cast_fu_2694_p1));

assign p_Val2_134_cast_fu_3102_p1 = $signed(tmp_92_fu_3092_p4);

assign p_Val2_134_fu_2744_p2 = ($signed(p_Val2_109_cast_fu_2728_p1) + $signed(p_Result_72_cast_fu_2740_p1));

assign p_Val2_135_fu_2790_p2 = ($signed(p_Val2_112_cast_fu_2774_p1) + $signed(p_Result_74_cast_fu_2786_p1));

assign p_Val2_136_cast_fu_3152_p1 = $signed(tmp_94_fu_3142_p4);

assign p_Val2_136_fu_2836_p2 = ($signed(p_Val2_115_cast_fu_2820_p1) + $signed(p_Result_76_cast_fu_2832_p1));

assign p_Val2_137_fu_2882_p2 = ($signed(p_Val2_118_cast_fu_2866_p1) + $signed(p_Result_78_cast_fu_2878_p1));

assign p_Val2_138_cast_fu_3202_p1 = $signed(tmp_96_fu_3192_p4);

assign p_Val2_138_fu_2928_p2 = ($signed(p_Val2_121_cast_fu_2912_p1) + $signed(p_Result_80_cast_fu_2924_p1));

assign p_Val2_139_fu_2974_p2 = ($signed(p_Val2_124_cast_fu_2958_p1) + $signed(p_Result_82_cast_fu_2970_p1));

assign p_Val2_13_cast_fu_1256_p1 = $signed(tmp_7_fu_1246_p4);

assign p_Val2_140_fu_2986_p2 = ($signed(p_Val2_126_cast_fu_2980_p1) + $signed(p_Result_84_cast_fu_2983_p1));

assign p_Val2_141_fu_3002_p2 = ($signed(p_Val2_128_cast_fu_2996_p1) + $signed(p_Result_86_cast_fu_2999_p1));

assign p_Val2_142_fu_3018_p2 = ($signed(p_Val2_130_cast_fu_3012_p1) + $signed(p_Result_88_cast_fu_3015_p1));

assign p_Val2_143_fu_3068_p2 = ($signed(p_Val2_132_cast_fu_3052_p1) + $signed(p_Result_90_cast_fu_3064_p1));

assign p_Val2_144_fu_3118_p2 = ($signed(p_Val2_134_cast_fu_3102_p1) + $signed(p_Result_92_cast_fu_3114_p1));

assign p_Val2_145_fu_3168_p2 = ($signed(p_Val2_136_cast_fu_3152_p1) + $signed(p_Result_94_cast_fu_3164_p1));

assign p_Val2_146_fu_3218_p2 = ($signed(p_Val2_138_cast_fu_3202_p1) + $signed(p_Result_96_cast_fu_3214_p1));

assign p_Val2_14_fu_1378_p0 = p_Val2_14_fu_1378_p00;

assign p_Val2_14_fu_1378_p00 = pixel_window_7_V;

assign p_Val2_14_fu_1378_p1 = kernel_patch_7_V;

assign p_Val2_14_fu_1378_p2 = ($signed({{1'b0}, {p_Val2_14_fu_1378_p0}}) * $signed(p_Val2_14_fu_1378_p1));

assign p_Val2_16_cast_fu_1302_p1 = $signed(tmp_10_fu_1292_p4);

assign p_Val2_16_fu_1424_p0 = p_Val2_16_fu_1424_p00;

assign p_Val2_16_fu_1424_p00 = pixel_window_8_V;

assign p_Val2_16_fu_1424_p1 = kernel_patch_8_V;

assign p_Val2_16_fu_1424_p2 = ($signed({{1'b0}, {p_Val2_16_fu_1424_p0}}) * $signed(p_Val2_16_fu_1424_p1));

assign p_Val2_188_cast_fu_3252_p1 = p_Val2_98_reg_3795;

assign p_Val2_189_cast_fu_3255_p1 = p_Val2_99_reg_3800;

assign p_Val2_18_fu_1470_p0 = p_Val2_18_fu_1470_p00;

assign p_Val2_18_fu_1470_p00 = pixel_window_9_V;

assign p_Val2_18_fu_1470_p1 = kernel_patch_9_V;

assign p_Val2_18_fu_1470_p2 = ($signed({{1'b0}, {p_Val2_18_fu_1470_p0}}) * $signed(p_Val2_18_fu_1470_p1));

assign p_Val2_190_cast_fu_3258_p1 = p_Val2_100_reg_3805;

assign p_Val2_191_6_fu_3745_p2 = (tmp24_fu_3739_p2 + tmp1_fu_3727_p2);

assign p_Val2_191_cast_fu_3261_p1 = p_Val2_101_reg_3810;

assign p_Val2_192_cast_fu_3264_p1 = p_Val2_102_reg_3815;

assign p_Val2_193_cast_fu_3267_p1 = p_Val2_103_reg_3820;

assign p_Val2_194_cast_fu_3270_p1 = p_Val2_104_reg_3825;

assign p_Val2_195_cast_fu_3273_p1 = p_Val2_105_reg_3830;

assign p_Val2_196_cast_fu_3276_p1 = p_Val2_106_reg_3835;

assign p_Val2_197_cast_fu_3279_p1 = p_Val2_107_reg_3840;

assign p_Val2_198_cast_fu_3282_p1 = p_Val2_108_reg_3845;

assign p_Val2_199_cast_fu_3285_p1 = p_Val2_109_reg_3850;

assign p_Val2_19_cast_fu_1348_p1 = $signed(tmp_12_fu_1338_p4);

assign p_Val2_1_cast_fu_1072_p1 = $signed(tmp_2_fu_1062_p4);

assign p_Val2_200_cast_fu_3288_p1 = p_Val2_110_reg_3855;

assign p_Val2_201_cast_fu_3291_p1 = p_Val2_111_reg_3860;

assign p_Val2_202_cast_fu_3294_p1 = p_Val2_112_reg_3865;

assign p_Val2_203_cast_fu_3297_p1 = p_Val2_113_reg_3870;

assign p_Val2_204_cast_fu_3300_p1 = p_Val2_114_reg_3875;

assign p_Val2_205_cast_fu_3303_p1 = p_Val2_115_reg_3880;

assign p_Val2_206_cast_fu_3306_p1 = p_Val2_116_reg_3885;

assign p_Val2_207_cast_fu_3309_p1 = p_Val2_117_reg_3890;

assign p_Val2_208_cast_fu_3312_p1 = p_Val2_118_reg_3895;

assign p_Val2_209_cast_fu_3315_p1 = p_Val2_119_reg_3900;

assign p_Val2_20_fu_1516_p0 = p_Val2_20_fu_1516_p00;

assign p_Val2_20_fu_1516_p00 = pixel_window_10_V;

assign p_Val2_20_fu_1516_p1 = kernel_patch_10_V;

assign p_Val2_20_fu_1516_p2 = ($signed({{1'b0}, {p_Val2_20_fu_1516_p0}}) * $signed(p_Val2_20_fu_1516_p1));

assign p_Val2_210_cast_fu_3318_p1 = p_Val2_120_reg_3905;

assign p_Val2_211_cast_fu_3321_p1 = p_Val2_121_reg_3910;

assign p_Val2_212_cast_fu_3324_p1 = p_Val2_122_reg_3915;

assign p_Val2_213_cast_fu_3327_p1 = p_Val2_123_reg_3920;

assign p_Val2_214_cast_fu_3330_p1 = p_Val2_124_reg_3925;

assign p_Val2_215_cast_fu_3333_p1 = p_Val2_125_reg_3930;

assign p_Val2_216_cast_fu_3336_p1 = p_Val2_126_reg_3935;

assign p_Val2_217_cast_fu_3339_p1 = p_Val2_127_reg_3940;

assign p_Val2_218_cast_fu_3342_p1 = p_Val2_128_reg_3945;

assign p_Val2_219_cast_fu_3345_p1 = p_Val2_129_reg_3950;

assign p_Val2_220_cast_fu_3348_p1 = p_Val2_130_reg_3955;

assign p_Val2_221_cast_fu_3351_p1 = p_Val2_131_reg_3960;

assign p_Val2_222_cast_fu_3354_p1 = p_Val2_132_reg_3965;

assign p_Val2_223_cast_fu_3357_p1 = p_Val2_133_reg_3970;

assign p_Val2_224_cast_fu_3360_p1 = p_Val2_134_reg_3975;

assign p_Val2_225_cast_fu_3363_p1 = p_Val2_135_reg_3980;

assign p_Val2_226_cast_fu_3366_p1 = p_Val2_136_reg_3985;

assign p_Val2_227_cast_fu_3369_p1 = p_Val2_137_reg_3990;

assign p_Val2_228_cast_fu_3372_p1 = p_Val2_138_reg_3995;

assign p_Val2_229_cast_fu_3375_p1 = p_Val2_139_reg_4000;

assign p_Val2_22_cast_fu_1394_p1 = $signed(tmp_14_fu_1384_p4);

assign p_Val2_22_fu_1562_p0 = p_Val2_22_fu_1562_p00;

assign p_Val2_22_fu_1562_p00 = pixel_window_11_V;

assign p_Val2_22_fu_1562_p1 = kernel_patch_11_V;

assign p_Val2_22_fu_1562_p2 = ($signed({{1'b0}, {p_Val2_22_fu_1562_p0}}) * $signed(p_Val2_22_fu_1562_p1));

assign p_Val2_230_cast_fu_2992_p1 = p_Val2_140_fu_2986_p2;

assign p_Val2_231_cast_fu_3008_p1 = p_Val2_141_fu_3002_p2;

assign p_Val2_232_cast_fu_3024_p1 = p_Val2_142_fu_3018_p2;

assign p_Val2_233_cast_fu_3074_p1 = p_Val2_143_fu_3068_p2;

assign p_Val2_234_cast_fu_3124_p1 = p_Val2_144_fu_3118_p2;

assign p_Val2_235_cast_fu_3174_p1 = p_Val2_145_fu_3168_p2;

assign p_Val2_236_cast_fu_3224_p1 = p_Val2_146_fu_3218_p2;

assign p_Val2_24_fu_1608_p0 = p_Val2_24_fu_1608_p00;

assign p_Val2_24_fu_1608_p00 = pixel_window_12_V;

assign p_Val2_24_fu_1608_p1 = kernel_patch_12_V;

assign p_Val2_24_fu_1608_p2 = ($signed({{1'b0}, {p_Val2_24_fu_1608_p0}}) * $signed(p_Val2_24_fu_1608_p1));

assign p_Val2_25_cast_fu_1440_p1 = $signed(tmp_16_fu_1430_p4);

assign p_Val2_26_fu_1654_p0 = p_Val2_26_fu_1654_p00;

assign p_Val2_26_fu_1654_p00 = pixel_window_13_V;

assign p_Val2_26_fu_1654_p1 = kernel_patch_13_V;

assign p_Val2_26_fu_1654_p2 = ($signed({{1'b0}, {p_Val2_26_fu_1654_p0}}) * $signed(p_Val2_26_fu_1654_p1));

assign p_Val2_28_cast_fu_1486_p1 = $signed(tmp_18_fu_1476_p4);

assign p_Val2_28_fu_1700_p0 = p_Val2_28_fu_1700_p00;

assign p_Val2_28_fu_1700_p00 = pixel_window_14_V;

assign p_Val2_28_fu_1700_p1 = kernel_patch_14_V;

assign p_Val2_28_fu_1700_p2 = ($signed({{1'b0}, {p_Val2_28_fu_1700_p0}}) * $signed(p_Val2_28_fu_1700_p1));

assign p_Val2_2_fu_1102_p0 = p_Val2_2_fu_1102_p00;

assign p_Val2_2_fu_1102_p00 = pixel_window_1_V;

assign p_Val2_2_fu_1102_p1 = kernel_patch_1_V;

assign p_Val2_2_fu_1102_p2 = ($signed({{1'b0}, {p_Val2_2_fu_1102_p0}}) * $signed(p_Val2_2_fu_1102_p1));

assign p_Val2_30_fu_1746_p0 = p_Val2_30_fu_1746_p00;

assign p_Val2_30_fu_1746_p00 = pixel_window_15_V;

assign p_Val2_30_fu_1746_p1 = kernel_patch_15_V;

assign p_Val2_30_fu_1746_p2 = ($signed({{1'b0}, {p_Val2_30_fu_1746_p0}}) * $signed(p_Val2_30_fu_1746_p1));

assign p_Val2_31_cast_fu_1532_p1 = $signed(tmp_20_fu_1522_p4);

assign p_Val2_32_fu_1792_p0 = p_Val2_32_fu_1792_p00;

assign p_Val2_32_fu_1792_p00 = pixel_window_16_V;

assign p_Val2_32_fu_1792_p1 = kernel_patch_16_V;

assign p_Val2_32_fu_1792_p2 = ($signed({{1'b0}, {p_Val2_32_fu_1792_p0}}) * $signed(p_Val2_32_fu_1792_p1));

assign p_Val2_34_cast_fu_1578_p1 = $signed(tmp_22_fu_1568_p4);

assign p_Val2_34_fu_1838_p0 = p_Val2_34_fu_1838_p00;

assign p_Val2_34_fu_1838_p00 = pixel_window_17_V;

assign p_Val2_34_fu_1838_p1 = kernel_patch_17_V;

assign p_Val2_34_fu_1838_p2 = ($signed({{1'b0}, {p_Val2_34_fu_1838_p0}}) * $signed(p_Val2_34_fu_1838_p1));

assign p_Val2_36_fu_1884_p0 = p_Val2_36_fu_1884_p00;

assign p_Val2_36_fu_1884_p00 = pixel_window_18_V;

assign p_Val2_36_fu_1884_p1 = kernel_patch_18_V;

assign p_Val2_36_fu_1884_p2 = ($signed({{1'b0}, {p_Val2_36_fu_1884_p0}}) * $signed(p_Val2_36_fu_1884_p1));

assign p_Val2_37_cast_fu_1624_p1 = $signed(tmp_24_fu_1614_p4);

assign p_Val2_38_fu_1930_p0 = p_Val2_38_fu_1930_p00;

assign p_Val2_38_fu_1930_p00 = pixel_window_19_V;

assign p_Val2_38_fu_1930_p1 = kernel_patch_19_V;

assign p_Val2_38_fu_1930_p2 = ($signed({{1'b0}, {p_Val2_38_fu_1930_p0}}) * $signed(p_Val2_38_fu_1930_p1));

assign p_Val2_40_cast_fu_1670_p1 = $signed(tmp_26_fu_1660_p4);

assign p_Val2_40_fu_1976_p0 = p_Val2_40_fu_1976_p00;

assign p_Val2_40_fu_1976_p00 = pixel_window_20_V;

assign p_Val2_40_fu_1976_p1 = kernel_patch_20_V;

assign p_Val2_40_fu_1976_p2 = ($signed({{1'b0}, {p_Val2_40_fu_1976_p0}}) * $signed(p_Val2_40_fu_1976_p1));

assign p_Val2_42_fu_2022_p0 = p_Val2_42_fu_2022_p00;

assign p_Val2_42_fu_2022_p00 = pixel_window_21_V;

assign p_Val2_42_fu_2022_p1 = kernel_patch_21_V;

assign p_Val2_42_fu_2022_p2 = ($signed({{1'b0}, {p_Val2_42_fu_2022_p0}}) * $signed(p_Val2_42_fu_2022_p1));

assign p_Val2_43_cast_fu_1716_p1 = $signed(tmp_28_fu_1706_p4);

assign p_Val2_44_fu_2068_p0 = p_Val2_44_fu_2068_p00;

assign p_Val2_44_fu_2068_p00 = pixel_window_22_V;

assign p_Val2_44_fu_2068_p1 = kernel_patch_22_V;

assign p_Val2_44_fu_2068_p2 = ($signed({{1'b0}, {p_Val2_44_fu_2068_p0}}) * $signed(p_Val2_44_fu_2068_p1));

assign p_Val2_46_cast_fu_1762_p1 = $signed(tmp_30_fu_1752_p4);

assign p_Val2_46_fu_2114_p0 = p_Val2_46_fu_2114_p00;

assign p_Val2_46_fu_2114_p00 = pixel_window_23_V;

assign p_Val2_46_fu_2114_p1 = kernel_patch_23_V;

assign p_Val2_46_fu_2114_p2 = ($signed({{1'b0}, {p_Val2_46_fu_2114_p0}}) * $signed(p_Val2_46_fu_2114_p1));

assign p_Val2_48_fu_2160_p0 = p_Val2_48_fu_2160_p00;

assign p_Val2_48_fu_2160_p00 = pixel_window_24_V;

assign p_Val2_48_fu_2160_p1 = kernel_patch_24_V;

assign p_Val2_48_fu_2160_p2 = ($signed({{1'b0}, {p_Val2_48_fu_2160_p0}}) * $signed(p_Val2_48_fu_2160_p1));

assign p_Val2_49_cast_fu_1808_p1 = $signed(tmp_32_fu_1798_p4);

assign p_Val2_4_cast_fu_1118_p1 = $signed(tmp_6_fu_1108_p4);

assign p_Val2_4_fu_1148_p0 = p_Val2_4_fu_1148_p00;

assign p_Val2_4_fu_1148_p00 = pixel_window_2_V;

assign p_Val2_4_fu_1148_p1 = kernel_patch_2_V;

assign p_Val2_4_fu_1148_p2 = ($signed({{1'b0}, {p_Val2_4_fu_1148_p0}}) * $signed(p_Val2_4_fu_1148_p1));

assign p_Val2_50_fu_2206_p0 = p_Val2_50_fu_2206_p00;

assign p_Val2_50_fu_2206_p00 = pixel_window_25_V;

assign p_Val2_50_fu_2206_p1 = kernel_patch_25_V;

assign p_Val2_50_fu_2206_p2 = ($signed({{1'b0}, {p_Val2_50_fu_2206_p0}}) * $signed(p_Val2_50_fu_2206_p1));

assign p_Val2_52_cast_fu_1854_p1 = $signed(tmp_34_fu_1844_p4);

assign p_Val2_52_fu_2252_p0 = p_Val2_52_fu_2252_p00;

assign p_Val2_52_fu_2252_p00 = pixel_window_26_V;

assign p_Val2_52_fu_2252_p1 = kernel_patch_26_V;

assign p_Val2_52_fu_2252_p2 = ($signed({{1'b0}, {p_Val2_52_fu_2252_p0}}) * $signed(p_Val2_52_fu_2252_p1));

assign p_Val2_54_fu_2298_p0 = p_Val2_54_fu_2298_p00;

assign p_Val2_54_fu_2298_p00 = pixel_window_27_V;

assign p_Val2_54_fu_2298_p1 = kernel_patch_27_V;

assign p_Val2_54_fu_2298_p2 = ($signed({{1'b0}, {p_Val2_54_fu_2298_p0}}) * $signed(p_Val2_54_fu_2298_p1));

assign p_Val2_55_cast_fu_1900_p1 = $signed(tmp_36_fu_1890_p4);

assign p_Val2_56_fu_2344_p0 = p_Val2_56_fu_2344_p00;

assign p_Val2_56_fu_2344_p00 = pixel_window_28_V;

assign p_Val2_56_fu_2344_p1 = kernel_patch_28_V;

assign p_Val2_56_fu_2344_p2 = ($signed({{1'b0}, {p_Val2_56_fu_2344_p0}}) * $signed(p_Val2_56_fu_2344_p1));

assign p_Val2_58_cast_fu_1946_p1 = $signed(tmp_38_fu_1936_p4);

assign p_Val2_58_fu_2390_p0 = p_Val2_58_fu_2390_p00;

assign p_Val2_58_fu_2390_p00 = pixel_window_29_V;

assign p_Val2_58_fu_2390_p1 = kernel_patch_29_V;

assign p_Val2_58_fu_2390_p2 = ($signed({{1'b0}, {p_Val2_58_fu_2390_p0}}) * $signed(p_Val2_58_fu_2390_p1));

assign p_Val2_60_fu_2436_p0 = p_Val2_60_fu_2436_p00;

assign p_Val2_60_fu_2436_p00 = pixel_window_30_V;

assign p_Val2_60_fu_2436_p1 = kernel_patch_30_V;

assign p_Val2_60_fu_2436_p2 = ($signed({{1'b0}, {p_Val2_60_fu_2436_p0}}) * $signed(p_Val2_60_fu_2436_p1));

assign p_Val2_61_cast_fu_1992_p1 = $signed(tmp_40_fu_1982_p4);

assign p_Val2_62_fu_2482_p0 = p_Val2_62_fu_2482_p00;

assign p_Val2_62_fu_2482_p00 = pixel_window_31_V;

assign p_Val2_62_fu_2482_p1 = kernel_patch_31_V;

assign p_Val2_62_fu_2482_p2 = ($signed({{1'b0}, {p_Val2_62_fu_2482_p0}}) * $signed(p_Val2_62_fu_2482_p1));

assign p_Val2_64_cast_fu_2038_p1 = $signed(tmp_42_fu_2028_p4);

assign p_Val2_64_fu_2528_p0 = p_Val2_64_fu_2528_p00;

assign p_Val2_64_fu_2528_p00 = pixel_window_32_V;

assign p_Val2_64_fu_2528_p1 = kernel_patch_32_V;

assign p_Val2_64_fu_2528_p2 = ($signed({{1'b0}, {p_Val2_64_fu_2528_p0}}) * $signed(p_Val2_64_fu_2528_p1));

assign p_Val2_66_fu_2574_p0 = p_Val2_66_fu_2574_p00;

assign p_Val2_66_fu_2574_p00 = pixel_window_33_V;

assign p_Val2_66_fu_2574_p1 = kernel_patch_33_V;

assign p_Val2_66_fu_2574_p2 = ($signed({{1'b0}, {p_Val2_66_fu_2574_p0}}) * $signed(p_Val2_66_fu_2574_p1));

assign p_Val2_67_cast_fu_2084_p1 = $signed(tmp_44_fu_2074_p4);

assign p_Val2_68_fu_2620_p0 = p_Val2_68_fu_2620_p00;

assign p_Val2_68_fu_2620_p00 = pixel_window_34_V;

assign p_Val2_68_fu_2620_p1 = kernel_patch_34_V;

assign p_Val2_68_fu_2620_p2 = ($signed({{1'b0}, {p_Val2_68_fu_2620_p0}}) * $signed(p_Val2_68_fu_2620_p1));

assign p_Val2_6_fu_1194_p0 = p_Val2_6_fu_1194_p00;

assign p_Val2_6_fu_1194_p00 = pixel_window_3_V;

assign p_Val2_6_fu_1194_p1 = kernel_patch_3_V;

assign p_Val2_6_fu_1194_p2 = ($signed({{1'b0}, {p_Val2_6_fu_1194_p0}}) * $signed(p_Val2_6_fu_1194_p1));

assign p_Val2_70_cast_fu_2130_p1 = $signed(tmp_46_fu_2120_p4);

assign p_Val2_70_fu_2666_p0 = p_Val2_70_fu_2666_p00;

assign p_Val2_70_fu_2666_p00 = pixel_window_35_V;

assign p_Val2_70_fu_2666_p1 = kernel_patch_35_V;

assign p_Val2_70_fu_2666_p2 = ($signed({{1'b0}, {p_Val2_70_fu_2666_p0}}) * $signed(p_Val2_70_fu_2666_p1));

assign p_Val2_72_fu_2712_p0 = p_Val2_72_fu_2712_p00;

assign p_Val2_72_fu_2712_p00 = pixel_window_36_V;

assign p_Val2_72_fu_2712_p1 = kernel_patch_36_V;

assign p_Val2_72_fu_2712_p2 = ($signed({{1'b0}, {p_Val2_72_fu_2712_p0}}) * $signed(p_Val2_72_fu_2712_p1));

assign p_Val2_73_cast_fu_2176_p1 = $signed(tmp_48_fu_2166_p4);

assign p_Val2_74_fu_2758_p0 = p_Val2_74_fu_2758_p00;

assign p_Val2_74_fu_2758_p00 = pixel_window_37_V;

assign p_Val2_74_fu_2758_p1 = kernel_patch_37_V;

assign p_Val2_74_fu_2758_p2 = ($signed({{1'b0}, {p_Val2_74_fu_2758_p0}}) * $signed(p_Val2_74_fu_2758_p1));

assign p_Val2_76_cast_fu_2222_p1 = $signed(tmp_50_fu_2212_p4);

assign p_Val2_76_fu_2804_p0 = p_Val2_76_fu_2804_p00;

assign p_Val2_76_fu_2804_p00 = pixel_window_38_V;

assign p_Val2_76_fu_2804_p1 = kernel_patch_38_V;

assign p_Val2_76_fu_2804_p2 = ($signed({{1'b0}, {p_Val2_76_fu_2804_p0}}) * $signed(p_Val2_76_fu_2804_p1));

assign p_Val2_78_fu_2850_p0 = p_Val2_78_fu_2850_p00;

assign p_Val2_78_fu_2850_p00 = pixel_window_39_V;

assign p_Val2_78_fu_2850_p1 = kernel_patch_39_V;

assign p_Val2_78_fu_2850_p2 = ($signed({{1'b0}, {p_Val2_78_fu_2850_p0}}) * $signed(p_Val2_78_fu_2850_p1));

assign p_Val2_79_cast_fu_2268_p1 = $signed(tmp_52_fu_2258_p4);

assign p_Val2_7_cast_fu_1164_p1 = $signed(tmp_s_fu_1154_p4);

assign p_Val2_80_fu_2896_p0 = p_Val2_80_fu_2896_p00;

assign p_Val2_80_fu_2896_p00 = pixel_window_40_V;

assign p_Val2_80_fu_2896_p1 = kernel_patch_40_V;

assign p_Val2_80_fu_2896_p2 = ($signed({{1'b0}, {p_Val2_80_fu_2896_p0}}) * $signed(p_Val2_80_fu_2896_p1));

assign p_Val2_82_cast_fu_2314_p1 = $signed(tmp_54_fu_2304_p4);

assign p_Val2_82_fu_2942_p0 = p_Val2_82_fu_2942_p00;

assign p_Val2_82_fu_2942_p00 = pixel_window_41_V;

assign p_Val2_82_fu_2942_p1 = kernel_patch_41_V;

assign p_Val2_82_fu_2942_p2 = ($signed({{1'b0}, {p_Val2_82_fu_2942_p0}}) * $signed(p_Val2_82_fu_2942_p1));

assign p_Val2_84_fu_960_p0 = p_Val2_84_fu_960_p00;

assign p_Val2_84_fu_960_p00 = pixel_window_42_V;

assign p_Val2_84_fu_960_p1 = kernel_patch_42_V;

assign p_Val2_84_fu_960_p2 = ($signed({{1'b0}, {p_Val2_84_fu_960_p0}}) * $signed(p_Val2_84_fu_960_p1));

assign p_Val2_85_cast_fu_2360_p1 = $signed(tmp_56_fu_2350_p4);

assign p_Val2_86_fu_992_p0 = p_Val2_86_fu_992_p00;

assign p_Val2_86_fu_992_p00 = pixel_window_43_V;

assign p_Val2_86_fu_992_p1 = kernel_patch_43_V;

assign p_Val2_86_fu_992_p2 = ($signed({{1'b0}, {p_Val2_86_fu_992_p0}}) * $signed(p_Val2_86_fu_992_p1));

assign p_Val2_88_cast_fu_2406_p1 = $signed(tmp_58_fu_2396_p4);

assign p_Val2_88_fu_1024_p0 = p_Val2_88_fu_1024_p00;

assign p_Val2_88_fu_1024_p00 = pixel_window_44_V;

assign p_Val2_88_fu_1024_p1 = kernel_patch_44_V;

assign p_Val2_88_fu_1024_p2 = ($signed({{1'b0}, {p_Val2_88_fu_1024_p0}}) * $signed(p_Val2_88_fu_1024_p1));

assign p_Val2_8_fu_1240_p0 = p_Val2_8_fu_1240_p00;

assign p_Val2_8_fu_1240_p00 = pixel_window_4_V;

assign p_Val2_8_fu_1240_p1 = kernel_patch_4_V;

assign p_Val2_8_fu_1240_p2 = ($signed({{1'b0}, {p_Val2_8_fu_1240_p0}}) * $signed(p_Val2_8_fu_1240_p1));

assign p_Val2_90_fu_3036_p0 = p_Val2_90_fu_3036_p00;

assign p_Val2_90_fu_3036_p00 = pixel_window_45_V;

assign p_Val2_90_fu_3036_p1 = kernel_patch_45_V;

assign p_Val2_90_fu_3036_p2 = ($signed({{1'b0}, {p_Val2_90_fu_3036_p0}}) * $signed(p_Val2_90_fu_3036_p1));

assign p_Val2_91_cast_fu_2452_p1 = $signed(tmp_60_fu_2442_p4);

assign p_Val2_92_fu_3086_p0 = p_Val2_92_fu_3086_p00;

assign p_Val2_92_fu_3086_p00 = pixel_window_46_V;

assign p_Val2_92_fu_3086_p1 = kernel_patch_46_V;

assign p_Val2_92_fu_3086_p2 = ($signed({{1'b0}, {p_Val2_92_fu_3086_p0}}) * $signed(p_Val2_92_fu_3086_p1));

assign p_Val2_94_cast_fu_2498_p1 = $signed(tmp_62_fu_2488_p4);

assign p_Val2_94_fu_3136_p0 = p_Val2_94_fu_3136_p00;

assign p_Val2_94_fu_3136_p00 = pixel_window_47_V;

assign p_Val2_94_fu_3136_p1 = kernel_patch_47_V;

assign p_Val2_94_fu_3136_p2 = ($signed({{1'b0}, {p_Val2_94_fu_3136_p0}}) * $signed(p_Val2_94_fu_3136_p1));

assign p_Val2_96_fu_3186_p0 = p_Val2_96_fu_3186_p00;

assign p_Val2_96_fu_3186_p00 = pixel_window_48_V;

assign p_Val2_96_fu_3186_p1 = kernel_patch_48_V;

assign p_Val2_96_fu_3186_p2 = ($signed({{1'b0}, {p_Val2_96_fu_3186_p0}}) * $signed(p_Val2_96_fu_3186_p1));

assign p_Val2_97_cast_fu_2544_p1 = $signed(tmp_64_fu_2534_p4);

assign p_Val2_98_fu_1088_p2 = ($signed(p_Val2_1_cast_fu_1072_p1) + $signed(p_Result_1_cast_fu_1084_p1));

assign p_Val2_99_fu_1134_p2 = ($signed(p_Val2_4_cast_fu_1118_p1) + $signed(p_Result_3_cast_fu_1130_p1));

assign p_Val2_s_fu_1056_p0 = p_Val2_s_fu_1056_p00;

assign p_Val2_s_fu_1056_p00 = pixel_window_0_V;

assign p_Val2_s_fu_1056_p1 = kernel_patch_0_V;

assign p_Val2_s_fu_1056_p2 = ($signed({{1'b0}, {p_Val2_s_fu_1056_p0}}) * $signed(p_Val2_s_fu_1056_p1));

assign sop_enable_read_read_fu_344_p2 = sop_enable;

assign storemerge1_fu_3751_p0 = sop_enable;

assign tmp10_fu_3420_p2 = ($signed(p_Val2_195_cast_fu_3273_p1) + $signed(p_Val2_196_cast_fu_3276_p1));

assign tmp11_cast_fu_3448_p1 = $signed(tmp11_fu_3442_p2);

assign tmp11_fu_3442_p2 = ($signed(tmp12_fu_3436_p2) + $signed(p_Val2_197_cast_fu_3279_p1));

assign tmp12_fu_3436_p2 = ($signed(p_Val2_198_cast_fu_3282_p1) + $signed(p_Val2_199_cast_fu_3285_p1));

assign tmp13_cast_fu_3724_p1 = $signed(tmp13_reg_4025);

assign tmp13_fu_3552_p2 = ($signed(tmp19_cast_fu_3548_p1) + $signed(tmp14_cast_fu_3506_p1));

assign tmp14_cast_fu_3506_p1 = $signed(tmp14_fu_3500_p2);

assign tmp14_fu_3500_p2 = ($signed(tmp17_cast_fu_3496_p1) + $signed(tmp15_cast_fu_3480_p1));

assign tmp15_cast_fu_3480_p1 = $signed(tmp15_fu_3474_p2);

assign tmp15_fu_3474_p2 = ($signed(tmp16_fu_3468_p2) + $signed(p_Val2_200_cast_fu_3288_p1));

assign tmp16_fu_3468_p2 = ($signed(p_Val2_201_cast_fu_3291_p1) + $signed(p_Val2_202_cast_fu_3294_p1));

assign tmp17_cast_fu_3496_p1 = $signed(tmp17_fu_3490_p2);

assign tmp17_fu_3490_p2 = ($signed(tmp18_fu_3484_p2) + $signed(p_Val2_203_cast_fu_3297_p1));

assign tmp18_fu_3484_p2 = ($signed(p_Val2_204_cast_fu_3300_p1) + $signed(p_Val2_205_cast_fu_3303_p1));

assign tmp19_cast_fu_3548_p1 = $signed(tmp19_fu_3542_p2);

assign tmp19_fu_3542_p2 = ($signed(tmp22_cast_fu_3538_p1) + $signed(tmp20_cast_fu_3522_p1));

assign tmp1_fu_3727_p2 = ($signed(tmp13_cast_fu_3724_p1) + $signed(tmp2_cast_fu_3721_p1));

assign tmp20_cast_fu_3522_p1 = $signed(tmp20_fu_3516_p2);

assign tmp20_fu_3516_p2 = ($signed(tmp21_fu_3510_p2) + $signed(p_Val2_206_cast_fu_3306_p1));

assign tmp21_fu_3510_p2 = ($signed(p_Val2_207_cast_fu_3309_p1) + $signed(p_Val2_208_cast_fu_3312_p1));

assign tmp22_cast_fu_3538_p1 = $signed(tmp22_fu_3532_p2);

assign tmp22_fu_3532_p2 = ($signed(tmp23_fu_3526_p2) + $signed(p_Val2_209_cast_fu_3315_p1));

assign tmp23_fu_3526_p2 = ($signed(p_Val2_210_cast_fu_3318_p1) + $signed(p_Val2_211_cast_fu_3321_p1));

assign tmp24_fu_3739_p2 = ($signed(tmp36_cast_fu_3736_p1) + $signed(tmp25_cast_fu_3733_p1));

assign tmp25_cast_fu_3733_p1 = $signed(tmp25_reg_4030);

assign tmp25_fu_3642_p2 = ($signed(tmp31_cast_fu_3638_p1) + $signed(tmp26_cast_fu_3596_p1));

assign tmp26_cast_fu_3596_p1 = $signed(tmp26_fu_3590_p2);

assign tmp26_fu_3590_p2 = ($signed(tmp29_cast_fu_3586_p1) + $signed(tmp27_cast_fu_3570_p1));

assign tmp27_cast_fu_3570_p1 = $signed(tmp27_fu_3564_p2);

assign tmp27_fu_3564_p2 = ($signed(tmp28_fu_3558_p2) + $signed(p_Val2_212_cast_fu_3324_p1));

assign tmp28_fu_3558_p2 = ($signed(p_Val2_213_cast_fu_3327_p1) + $signed(p_Val2_214_cast_fu_3330_p1));

assign tmp29_cast_fu_3586_p1 = $signed(tmp29_fu_3580_p2);

assign tmp29_fu_3580_p2 = ($signed(tmp30_fu_3574_p2) + $signed(p_Val2_215_cast_fu_3333_p1));

assign tmp2_cast_fu_3721_p1 = $signed(tmp2_reg_4020);

assign tmp2_fu_3462_p2 = ($signed(tmp8_cast_fu_3458_p1) + $signed(tmp3_cast_fu_3416_p1));

assign tmp30_fu_3574_p2 = ($signed(p_Val2_216_cast_fu_3336_p1) + $signed(p_Val2_217_cast_fu_3339_p1));

assign tmp31_cast_fu_3638_p1 = $signed(tmp31_fu_3632_p2);

assign tmp31_fu_3632_p2 = ($signed(tmp34_cast_fu_3628_p1) + $signed(tmp32_cast_fu_3612_p1));

assign tmp32_cast_fu_3612_p1 = $signed(tmp32_fu_3606_p2);

assign tmp32_fu_3606_p2 = ($signed(tmp33_fu_3600_p2) + $signed(p_Val2_218_cast_fu_3342_p1));

assign tmp33_fu_3600_p2 = ($signed(p_Val2_219_cast_fu_3345_p1) + $signed(p_Val2_220_cast_fu_3348_p1));

assign tmp34_cast_fu_3628_p1 = $signed(tmp34_fu_3622_p2);

assign tmp34_fu_3622_p2 = ($signed(tmp35_fu_3616_p2) + $signed(p_Val2_221_cast_fu_3351_p1));

assign tmp35_fu_3616_p2 = ($signed(p_Val2_222_cast_fu_3354_p1) + $signed(p_Val2_223_cast_fu_3357_p1));

assign tmp36_cast_fu_3736_p1 = $signed(tmp36_reg_4035);

assign tmp36_fu_3715_p2 = ($signed(tmp42_cast_fu_3711_p1) + $signed(tmp37_cast_fu_3686_p1));

assign tmp37_cast_fu_3686_p1 = $signed(tmp37_fu_3680_p2);

assign tmp37_fu_3680_p2 = ($signed(tmp40_cast_fu_3676_p1) + $signed(tmp38_cast_fu_3660_p1));

assign tmp38_cast_fu_3660_p1 = $signed(tmp38_fu_3654_p2);

assign tmp38_fu_3654_p2 = ($signed(tmp39_fu_3648_p2) + $signed(p_Val2_224_cast_fu_3360_p1));

assign tmp39_fu_3648_p2 = ($signed(p_Val2_225_cast_fu_3363_p1) + $signed(p_Val2_226_cast_fu_3366_p1));

assign tmp3_cast_fu_3416_p1 = $signed(tmp3_fu_3410_p2);

assign tmp3_fu_3410_p2 = ($signed(tmp6_cast_fu_3406_p1) + $signed(tmp4_cast_fu_3390_p1));

assign tmp40_cast_fu_3676_p1 = $signed(tmp40_fu_3670_p2);

assign tmp40_fu_3670_p2 = ($signed(tmp41_fu_3664_p2) + $signed(p_Val2_227_cast_fu_3369_p1));

assign tmp41_fu_3664_p2 = ($signed(p_Val2_228_cast_fu_3372_p1) + $signed(p_Val2_229_cast_fu_3375_p1));

assign tmp42_cast_fu_3711_p1 = $signed(tmp42_fu_3705_p2);

assign tmp42_fu_3705_p2 = ($signed(tmp45_fu_3699_p2) + $signed(tmp43_cast_fu_3690_p1));

assign tmp43_cast_fu_3690_p1 = $signed(tmp43_reg_4005);

assign tmp43_fu_3234_p2 = ($signed(tmp44_fu_3228_p2) + $signed(p_Val2_230_cast_fu_2992_p1));

assign tmp44_fu_3228_p2 = ($signed(p_Val2_231_cast_fu_3008_p1) + $signed(p_Val2_232_cast_fu_3024_p1));

assign tmp45_fu_3699_p2 = ($signed(tmp47_cast_fu_3696_p1) + $signed(tmp46_cast_fu_3693_p1));

assign tmp46_cast_fu_3693_p1 = $signed(tmp46_reg_4010);

assign tmp46_fu_3240_p2 = ($signed(p_Val2_233_cast_fu_3074_p1) + $signed(p_Val2_234_cast_fu_3124_p1));

assign tmp47_cast_fu_3696_p1 = $signed(tmp47_reg_4015);

assign tmp47_fu_3246_p2 = ($signed(p_Val2_235_cast_fu_3174_p1) + $signed(p_Val2_236_cast_fu_3224_p1));

assign tmp4_cast_fu_3390_p1 = $signed(tmp4_fu_3384_p2);

assign tmp4_fu_3384_p2 = ($signed(tmp5_fu_3378_p2) + $signed(p_Val2_189_cast_fu_3255_p1));

assign tmp5_fu_3378_p2 = ($signed(p_Val2_188_cast_fu_3252_p1) + $signed(p_Val2_190_cast_fu_3258_p1));

assign tmp6_cast_fu_3406_p1 = $signed(tmp6_fu_3400_p2);

assign tmp6_fu_3400_p2 = ($signed(tmp7_fu_3394_p2) + $signed(p_Val2_191_cast_fu_3261_p1));

assign tmp7_fu_3394_p2 = ($signed(p_Val2_192_cast_fu_3264_p1) + $signed(p_Val2_193_cast_fu_3267_p1));

assign tmp8_cast_fu_3458_p1 = $signed(tmp8_fu_3452_p2);

assign tmp8_fu_3452_p2 = ($signed(tmp11_cast_fu_3448_p1) + $signed(tmp9_cast_fu_3432_p1));

assign tmp9_cast_fu_3432_p1 = $signed(tmp9_fu_3426_p2);

assign tmp9_fu_3426_p2 = ($signed(tmp10_fu_3420_p2) + $signed(p_Val2_194_cast_fu_3270_p1));

assign tmp_100_fu_1214_p3 = p_Val2_6_fu_1194_p2[32'd4];

assign tmp_101_fu_1260_p3 = p_Val2_8_fu_1240_p2[32'd4];

assign tmp_102_fu_1306_p3 = p_Val2_10_fu_1286_p2[32'd4];

assign tmp_103_fu_1352_p3 = p_Val2_12_fu_1332_p2[32'd4];

assign tmp_104_fu_1398_p3 = p_Val2_14_fu_1378_p2[32'd4];

assign tmp_105_fu_1444_p3 = p_Val2_16_fu_1424_p2[32'd4];

assign tmp_106_fu_1490_p3 = p_Val2_18_fu_1470_p2[32'd4];

assign tmp_107_fu_1536_p3 = p_Val2_20_fu_1516_p2[32'd4];

assign tmp_108_fu_1582_p3 = p_Val2_22_fu_1562_p2[32'd4];

assign tmp_109_fu_1628_p3 = p_Val2_24_fu_1608_p2[32'd4];

assign tmp_10_fu_1292_p4 = {{p_Val2_10_fu_1286_p2[15:5]}};

assign tmp_110_fu_1674_p3 = p_Val2_26_fu_1654_p2[32'd4];

assign tmp_111_fu_1720_p3 = p_Val2_28_fu_1700_p2[32'd4];

assign tmp_112_fu_1766_p3 = p_Val2_30_fu_1746_p2[32'd4];

assign tmp_113_fu_1812_p3 = p_Val2_32_fu_1792_p2[32'd4];

assign tmp_114_fu_1858_p3 = p_Val2_34_fu_1838_p2[32'd4];

assign tmp_115_fu_1904_p3 = p_Val2_36_fu_1884_p2[32'd4];

assign tmp_116_fu_1950_p3 = p_Val2_38_fu_1930_p2[32'd4];

assign tmp_117_fu_1996_p3 = p_Val2_40_fu_1976_p2[32'd4];

assign tmp_118_fu_2042_p3 = p_Val2_42_fu_2022_p2[32'd4];

assign tmp_119_fu_2088_p3 = p_Val2_44_fu_2068_p2[32'd4];

assign tmp_120_fu_2134_p3 = p_Val2_46_fu_2114_p2[32'd4];

assign tmp_121_fu_2180_p3 = p_Val2_48_fu_2160_p2[32'd4];

assign tmp_122_fu_2226_p3 = p_Val2_50_fu_2206_p2[32'd4];

assign tmp_123_fu_2272_p3 = p_Val2_52_fu_2252_p2[32'd4];

assign tmp_124_fu_2318_p3 = p_Val2_54_fu_2298_p2[32'd4];

assign tmp_125_fu_2364_p3 = p_Val2_56_fu_2344_p2[32'd4];

assign tmp_126_fu_2410_p3 = p_Val2_58_fu_2390_p2[32'd4];

assign tmp_127_fu_2456_p3 = p_Val2_60_fu_2436_p2[32'd4];

assign tmp_128_fu_2502_p3 = p_Val2_62_fu_2482_p2[32'd4];

assign tmp_129_fu_2548_p3 = p_Val2_64_fu_2528_p2[32'd4];

assign tmp_12_fu_1338_p4 = {{p_Val2_12_fu_1332_p2[15:5]}};

assign tmp_130_fu_2594_p3 = p_Val2_66_fu_2574_p2[32'd4];

assign tmp_131_fu_2640_p3 = p_Val2_68_fu_2620_p2[32'd4];

assign tmp_132_fu_2686_p3 = p_Val2_70_fu_2666_p2[32'd4];

assign tmp_133_fu_2732_p3 = p_Val2_72_fu_2712_p2[32'd4];

assign tmp_134_fu_2778_p3 = p_Val2_74_fu_2758_p2[32'd4];

assign tmp_135_fu_2824_p3 = p_Val2_76_fu_2804_p2[32'd4];

assign tmp_136_fu_2870_p3 = p_Val2_78_fu_2850_p2[32'd4];

assign tmp_137_fu_2916_p3 = p_Val2_80_fu_2896_p2[32'd4];

assign tmp_138_fu_2962_p3 = p_Val2_82_fu_2942_p2[32'd4];

assign tmp_142_fu_3056_p3 = p_Val2_90_fu_3036_p2[32'd4];

assign tmp_143_fu_3106_p3 = p_Val2_92_fu_3086_p2[32'd4];

assign tmp_144_fu_3156_p3 = p_Val2_94_fu_3136_p2[32'd4];

assign tmp_145_fu_3206_p3 = p_Val2_96_fu_3186_p2[32'd4];

assign tmp_14_fu_1384_p4 = {{p_Val2_14_fu_1378_p2[15:5]}};

assign tmp_16_fu_1430_p4 = {{p_Val2_16_fu_1424_p2[15:5]}};

assign tmp_18_fu_1476_p4 = {{p_Val2_18_fu_1470_p2[15:5]}};

assign tmp_1_fu_1200_p4 = {{p_Val2_6_fu_1194_p2[15:5]}};

assign tmp_20_fu_1522_p4 = {{p_Val2_20_fu_1516_p2[15:5]}};

assign tmp_22_fu_1568_p4 = {{p_Val2_22_fu_1562_p2[15:5]}};

assign tmp_24_fu_1614_p4 = {{p_Val2_24_fu_1608_p2[15:5]}};

assign tmp_26_fu_1660_p4 = {{p_Val2_26_fu_1654_p2[15:5]}};

assign tmp_28_fu_1706_p4 = {{p_Val2_28_fu_1700_p2[15:5]}};

assign tmp_2_fu_1062_p4 = {{p_Val2_s_fu_1056_p2[15:5]}};

assign tmp_30_fu_1752_p4 = {{p_Val2_30_fu_1746_p2[15:5]}};

assign tmp_32_fu_1798_p4 = {{p_Val2_32_fu_1792_p2[15:5]}};

assign tmp_34_fu_1844_p4 = {{p_Val2_34_fu_1838_p2[15:5]}};

assign tmp_36_fu_1890_p4 = {{p_Val2_36_fu_1884_p2[15:5]}};

assign tmp_38_fu_1936_p4 = {{p_Val2_38_fu_1930_p2[15:5]}};

assign tmp_40_fu_1982_p4 = {{p_Val2_40_fu_1976_p2[15:5]}};

assign tmp_42_fu_2028_p4 = {{p_Val2_42_fu_2022_p2[15:5]}};

assign tmp_44_fu_2074_p4 = {{p_Val2_44_fu_2068_p2[15:5]}};

assign tmp_46_fu_2120_p4 = {{p_Val2_46_fu_2114_p2[15:5]}};

assign tmp_48_fu_2166_p4 = {{p_Val2_48_fu_2160_p2[15:5]}};

assign tmp_50_fu_2212_p4 = {{p_Val2_50_fu_2206_p2[15:5]}};

assign tmp_52_fu_2258_p4 = {{p_Val2_52_fu_2252_p2[15:5]}};

assign tmp_54_fu_2304_p4 = {{p_Val2_54_fu_2298_p2[15:5]}};

assign tmp_56_fu_2350_p4 = {{p_Val2_56_fu_2344_p2[15:5]}};

assign tmp_58_fu_2396_p4 = {{p_Val2_58_fu_2390_p2[15:5]}};

assign tmp_60_fu_2442_p4 = {{p_Val2_60_fu_2436_p2[15:5]}};

assign tmp_62_fu_2488_p4 = {{p_Val2_62_fu_2482_p2[15:5]}};

assign tmp_64_fu_2534_p4 = {{p_Val2_64_fu_2528_p2[15:5]}};

assign tmp_66_fu_2580_p4 = {{p_Val2_66_fu_2574_p2[15:5]}};

assign tmp_68_fu_2626_p4 = {{p_Val2_68_fu_2620_p2[15:5]}};

assign tmp_6_fu_1108_p4 = {{p_Val2_2_fu_1102_p2[15:5]}};

assign tmp_70_fu_2672_p4 = {{p_Val2_70_fu_2666_p2[15:5]}};

assign tmp_72_fu_2718_p4 = {{p_Val2_72_fu_2712_p2[15:5]}};

assign tmp_74_fu_2764_p4 = {{p_Val2_74_fu_2758_p2[15:5]}};

assign tmp_76_fu_2810_p4 = {{p_Val2_76_fu_2804_p2[15:5]}};

assign tmp_78_fu_2856_p4 = {{p_Val2_78_fu_2850_p2[15:5]}};

assign tmp_7_fu_1246_p4 = {{p_Val2_8_fu_1240_p2[15:5]}};

assign tmp_80_fu_2902_p4 = {{p_Val2_80_fu_2896_p2[15:5]}};

assign tmp_82_fu_2948_p4 = {{p_Val2_82_fu_2942_p2[15:5]}};

assign tmp_90_fu_3042_p4 = {{p_Val2_90_fu_3036_p2[15:5]}};

assign tmp_92_fu_3092_p4 = {{p_Val2_92_fu_3086_p2[15:5]}};

assign tmp_94_fu_3142_p4 = {{p_Val2_94_fu_3136_p2[15:5]}};

assign tmp_96_fu_3192_p4 = {{p_Val2_96_fu_3186_p2[15:5]}};

assign tmp_97_fu_1076_p3 = p_Val2_s_fu_1056_p2[32'd4];

assign tmp_98_fu_1122_p3 = p_Val2_2_fu_1102_p2[32'd4];

assign tmp_99_fu_1168_p3 = p_Val2_4_fu_1148_p2[32'd4];

assign tmp_s_fu_1154_p4 = {{p_Val2_4_fu_1148_p2[15:5]}};

endmodule //fp_sop
